apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unifai.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unifai.labels" . | nindent 4 }}
data:
  config.json: |
    {{- include "unifai.config" . | nindent 4 }}