/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as WorkspaceLayoutRouteImport } from './workspace/layout'
import { Route as SignupLayoutRouteImport } from './signup/layout'
import { Route as PprofLayoutRouteImport } from './pprof/layout'
import { Route as LoginLayoutRouteImport } from './login/layout'
import { Route as IndexLayoutRouteImport } from './index/layout'
import { Route as WorkspaceVirtualKeysLayoutRouteImport } from './workspace/virtual-keys/layout'
import { Route as WorkspaceSkillsRepoLayoutRouteImport } from './workspace/skills-repo/layout'
import { Route as WorkspaceScimLayoutRouteImport } from './workspace/scim/layout'
import { Route as WorkspaceRoutingRulesLayoutRouteImport } from './workspace/routing-rules/layout'
import { Route as WorkspaceRbacLayoutRouteImport } from './workspace/rbac/layout'
import { Route as WorkspaceProvidersLayoutRouteImport } from './workspace/providers/layout'
import { Route as WorkspacePromptRepoLayoutRouteImport } from './workspace/prompt-repo/layout'
import { Route as WorkspacePluginsLayoutRouteImport } from './workspace/plugins/layout'
import { Route as WorkspaceObservabilityLayoutRouteImport } from './workspace/observability/layout'
import { Route as WorkspaceOauthGrantsLayoutRouteImport } from './workspace/oauth-grants/layout'
import { Route as WorkspaceModelLimitsLayoutRouteImport } from './workspace/model-limits/layout'
import { Route as WorkspaceModelCatalogLayoutRouteImport } from './workspace/model-catalog/layout'
import { Route as WorkspaceMcpToolGroupsLayoutRouteImport } from './workspace/mcp-tool-groups/layout'
import { Route as WorkspaceMcpSettingsLayoutRouteImport } from './workspace/mcp-settings/layout'
import { Route as WorkspaceMcpSessionsLayoutRouteImport } from './workspace/mcp-sessions/layout'
import { Route as WorkspaceMcpRegistryLayoutRouteImport } from './workspace/mcp-registry/layout'
import { Route as WorkspaceMcpLogsLayoutRouteImport } from './workspace/mcp-logs/layout'
import { Route as WorkspaceMcpGatewayLayoutRouteImport } from './workspace/mcp-gateway/layout'
import { Route as WorkspaceMcpAuthConfigLayoutRouteImport } from './workspace/mcp-auth-config/layout'
import { Route as WorkspaceLogsLayoutRouteImport } from './workspace/logs/layout'
import { Route as WorkspaceGuardrailsLayoutRouteImport } from './workspace/guardrails/layout'
import { Route as WorkspaceGovernanceLayoutRouteImport } from './workspace/governance/layout'
import { Route as WorkspaceDocsLayoutRouteImport } from './workspace/docs/layout'
import { Route as WorkspaceDashboardLayoutRouteImport } from './workspace/dashboard/layout'
import { Route as WorkspaceCustomPricingLayoutRouteImport } from './workspace/custom-pricing/layout'
import { Route as WorkspaceConfigLayoutRouteImport } from './workspace/config/layout'
import { Route as WorkspaceComplexityRouterLayoutRouteImport } from './workspace/complexity-router/layout'
import { Route as WorkspaceClusterLayoutRouteImport } from './workspace/cluster/layout'
import { Route as WorkspaceCircuitBreakerLayoutRouteImport } from './workspace/circuit-breaker/layout'
import { Route as WorkspaceBrowserAiLayoutRouteImport } from './workspace/browser-ai/layout'
import { Route as WorkspaceAuditLogsLayoutRouteImport } from './workspace/audit-logs/layout'
import { Route as WorkspaceAlertChannelsLayoutRouteImport } from './workspace/alert-channels/layout'
import { Route as WorkspaceAdaptiveRoutingLayoutRouteImport } from './workspace/adaptive-routing/layout'
import { Route as OauthConsentLayoutRouteImport } from './oauth/consent/layout'
import { Route as WorkspaceScimOauthDiscoverCallbackLayoutRouteImport } from './workspace/scim/oauth-discover-callback/layout'
import { Route as WorkspaceRoutingRulesTreeLayoutRouteImport } from './workspace/routing-rules/tree/layout'
import { Route as WorkspaceProvidersRoutingRulesLayoutRouteImport } from './workspace/providers/routing-rules/layout'
import { Route as WorkspaceProvidersModelLimitsLayoutRouteImport } from './workspace/providers/model-limits/layout'
import { Route as WorkspacePromptRepoPromptsLayoutRouteImport } from './workspace/prompt-repo/prompts/layout'
import { Route as WorkspaceMcpSessionsAuthSuccessLayoutRouteImport } from './workspace/mcp-sessions/auth-success/layout'
import { Route as WorkspaceMcpSessionsAuthFailedLayoutRouteImport } from './workspace/mcp-sessions/auth-failed/layout'
import { Route as WorkspaceMcpSessionsAuthLayoutRouteImport } from './workspace/mcp-sessions/auth/layout'
import { Route as WorkspaceMcpRegistryOauthCallbackLayoutRouteImport } from './workspace/mcp-registry/oauth-callback/layout'
import { Route as WorkspaceMcpRegistryLibraryLayoutRouteImport } from './workspace/mcp-registry/library/layout'
import { Route as WorkspaceLogsMcpLogsLayoutRouteImport } from './workspace/logs/mcp-logs/layout'
import { Route as WorkspaceLogsConnectorsLayoutRouteImport } from './workspace/logs/connectors/layout'
import { Route as WorkspaceGuardrailsProvidersLayoutRouteImport } from './workspace/guardrails/providers/layout'
import { Route as WorkspaceGuardrailsConfigurationLayoutRouteImport } from './workspace/guardrails/configuration/layout'
import { Route as WorkspaceGovernanceVirtualKeysLayoutRouteImport } from './workspace/governance/virtual-keys/layout'
import { Route as WorkspaceGovernanceUsersLayoutRouteImport } from './workspace/governance/users/layout'
import { Route as WorkspaceGovernanceTeamsLayoutRouteImport } from './workspace/governance/teams/layout'
import { Route as WorkspaceGovernanceRbacLayoutRouteImport } from './workspace/governance/rbac/layout'
import { Route as WorkspaceGovernanceCustomersLayoutRouteImport } from './workspace/governance/customers/layout'
import { Route as WorkspaceGovernanceBusinessUnitsLayoutRouteImport } from './workspace/governance/business-units/layout'
import { Route as WorkspaceGovernanceAccessProfilesLayoutRouteImport } from './workspace/governance/access-profiles/layout'
import { Route as WorkspaceCustomPricingOverridesLayoutRouteImport } from './workspace/custom-pricing/overrides/layout'
import { Route as WorkspaceConfigSecurityLayoutRouteImport } from './workspace/config/security/layout'
import { Route as WorkspaceConfigProxyLayoutRouteImport } from './workspace/config/proxy/layout'
import { Route as WorkspaceConfigPricingConfigLayoutRouteImport } from './workspace/config/pricing-config/layout'
import { Route as WorkspaceConfigPerformanceTuningLayoutRouteImport } from './workspace/config/performance-tuning/layout'
import { Route as WorkspaceConfigObservabilityLayoutRouteImport } from './workspace/config/observability/layout'
import { Route as WorkspaceConfigMcpGatewayLayoutRouteImport } from './workspace/config/mcp-gateway/layout'
import { Route as WorkspaceConfigLoggingLayoutRouteImport } from './workspace/config/logging/layout'
import { Route as WorkspaceConfigLargePayloadLayoutRouteImport } from './workspace/config/large-payload/layout'
import { Route as WorkspaceConfigFeatureFlagsLayoutRouteImport } from './workspace/config/feature-flags/layout'
import { Route as WorkspaceConfigCompatibilityLayoutRouteImport } from './workspace/config/compatibility/layout'
import { Route as WorkspaceConfigClientSettingsLayoutRouteImport } from './workspace/config/client-settings/layout'
import { Route as WorkspaceConfigCachingLayoutRouteImport } from './workspace/config/caching/layout'
import { Route as WorkspaceConfigApiKeysLayoutRouteImport } from './workspace/config/api-keys/layout'
import { Route as WorkspaceAdaptiveRoutingSettingsLayoutRouteImport } from './workspace/adaptive-routing/settings/layout'

const WorkspaceLayoutRoute = WorkspaceLayoutRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupLayoutRoute = SignupLayoutRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PprofLayoutRoute = PprofLayoutRouteImport.update({
  id: '/pprof',
  path: '/pprof',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginLayoutRoute = LoginLayoutRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLayoutRoute = IndexLayoutRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceVirtualKeysLayoutRoute =
  WorkspaceVirtualKeysLayoutRouteImport.update({
    id: '/virtual-keys',
    path: '/virtual-keys',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceSkillsRepoLayoutRoute =
  WorkspaceSkillsRepoLayoutRouteImport.update({
    id: '/skills-repo',
    path: '/skills-repo',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceScimLayoutRoute = WorkspaceScimLayoutRouteImport.update({
  id: '/scim',
  path: '/scim',
  getParentRoute: () => WorkspaceLayoutRoute,
} as any)
const WorkspaceRoutingRulesLayoutRoute =
  WorkspaceRoutingRulesLayoutRouteImport.update({
    id: '/routing-rules',
    path: '/routing-rules',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceRbacLayoutRoute = WorkspaceRbacLayoutRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => WorkspaceLayoutRoute,
} as any)
const WorkspaceProvidersLayoutRoute =
  WorkspaceProvidersLayoutRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspacePromptRepoLayoutRoute =
  WorkspacePromptRepoLayoutRouteImport.update({
    id: '/prompt-repo',
    path: '/prompt-repo',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspacePluginsLayoutRoute = WorkspacePluginsLayoutRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => WorkspaceLayoutRoute,
} as any)
const WorkspaceObservabilityLayoutRoute =
  WorkspaceObservabilityLayoutRouteImport.update({
    id: '/observability',
    path: '/observability',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceOauthGrantsLayoutRoute =
  WorkspaceOauthGrantsLayoutRouteImport.update({
    id: '/oauth-grants',
    path: '/oauth-grants',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceModelLimitsLayoutRoute =
  WorkspaceModelLimitsLayoutRouteImport.update({
    id: '/model-limits',
    path: '/model-limits',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceModelCatalogLayoutRoute =
  WorkspaceModelCatalogLayoutRouteImport.update({
    id: '/model-catalog',
    path: '/model-catalog',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceMcpToolGroupsLayoutRoute =
  WorkspaceMcpToolGroupsLayoutRouteImport.update({
    id: '/mcp-tool-groups',
    path: '/mcp-tool-groups',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceMcpSettingsLayoutRoute =
  WorkspaceMcpSettingsLayoutRouteImport.update({
    id: '/mcp-settings',
    path: '/mcp-settings',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceMcpSessionsLayoutRoute =
  WorkspaceMcpSessionsLayoutRouteImport.update({
    id: '/mcp-sessions',
    path: '/mcp-sessions',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceMcpRegistryLayoutRoute =
  WorkspaceMcpRegistryLayoutRouteImport.update({
    id: '/mcp-registry',
    path: '/mcp-registry',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceMcpLogsLayoutRoute = WorkspaceMcpLogsLayoutRouteImport.update({
  id: '/mcp-logs',
  path: '/mcp-logs',
  getParentRoute: () => WorkspaceLayoutRoute,
} as any)
const WorkspaceMcpGatewayLayoutRoute =
  WorkspaceMcpGatewayLayoutRouteImport.update({
    id: '/mcp-gateway',
    path: '/mcp-gateway',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceMcpAuthConfigLayoutRoute =
  WorkspaceMcpAuthConfigLayoutRouteImport.update({
    id: '/mcp-auth-config',
    path: '/mcp-auth-config',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceLogsLayoutRoute = WorkspaceLogsLayoutRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => WorkspaceLayoutRoute,
} as any)
const WorkspaceGuardrailsLayoutRoute =
  WorkspaceGuardrailsLayoutRouteImport.update({
    id: '/guardrails',
    path: '/guardrails',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceGovernanceLayoutRoute =
  WorkspaceGovernanceLayoutRouteImport.update({
    id: '/governance',
    path: '/governance',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceDocsLayoutRoute = WorkspaceDocsLayoutRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => WorkspaceLayoutRoute,
} as any)
const WorkspaceDashboardLayoutRoute =
  WorkspaceDashboardLayoutRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceCustomPricingLayoutRoute =
  WorkspaceCustomPricingLayoutRouteImport.update({
    id: '/custom-pricing',
    path: '/custom-pricing',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceConfigLayoutRoute = WorkspaceConfigLayoutRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => WorkspaceLayoutRoute,
} as any)
const WorkspaceComplexityRouterLayoutRoute =
  WorkspaceComplexityRouterLayoutRouteImport.update({
    id: '/complexity-router',
    path: '/complexity-router',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceClusterLayoutRoute = WorkspaceClusterLayoutRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => WorkspaceLayoutRoute,
} as any)
const WorkspaceCircuitBreakerLayoutRoute =
  WorkspaceCircuitBreakerLayoutRouteImport.update({
    id: '/circuit-breaker',
    path: '/circuit-breaker',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceBrowserAiLayoutRoute =
  WorkspaceBrowserAiLayoutRouteImport.update({
    id: '/browser-ai',
    path: '/browser-ai',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceAuditLogsLayoutRoute =
  WorkspaceAuditLogsLayoutRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceAlertChannelsLayoutRoute =
  WorkspaceAlertChannelsLayoutRouteImport.update({
    id: '/alert-channels',
    path: '/alert-channels',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const WorkspaceAdaptiveRoutingLayoutRoute =
  WorkspaceAdaptiveRoutingLayoutRouteImport.update({
    id: '/adaptive-routing',
    path: '/adaptive-routing',
    getParentRoute: () => WorkspaceLayoutRoute,
  } as any)
const OauthConsentLayoutRoute = OauthConsentLayoutRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceScimOauthDiscoverCallbackLayoutRoute =
  WorkspaceScimOauthDiscoverCallbackLayoutRouteImport.update({
    id: '/oauth-discover-callback',
    path: '/oauth-discover-callback',
    getParentRoute: () => WorkspaceScimLayoutRoute,
  } as any)
const WorkspaceRoutingRulesTreeLayoutRoute =
  WorkspaceRoutingRulesTreeLayoutRouteImport.update({
    id: '/tree',
    path: '/tree',
    getParentRoute: () => WorkspaceRoutingRulesLayoutRoute,
  } as any)
const WorkspaceProvidersRoutingRulesLayoutRoute =
  WorkspaceProvidersRoutingRulesLayoutRouteImport.update({
    id: '/routing-rules',
    path: '/routing-rules',
    getParentRoute: () => WorkspaceProvidersLayoutRoute,
  } as any)
const WorkspaceProvidersModelLimitsLayoutRoute =
  WorkspaceProvidersModelLimitsLayoutRouteImport.update({
    id: '/model-limits',
    path: '/model-limits',
    getParentRoute: () => WorkspaceProvidersLayoutRoute,
  } as any)
const WorkspacePromptRepoPromptsLayoutRoute =
  WorkspacePromptRepoPromptsLayoutRouteImport.update({
    id: '/prompts',
    path: '/prompts',
    getParentRoute: () => WorkspacePromptRepoLayoutRoute,
  } as any)
const WorkspaceMcpSessionsAuthSuccessLayoutRoute =
  WorkspaceMcpSessionsAuthSuccessLayoutRouteImport.update({
    id: '/auth-success',
    path: '/auth-success',
    getParentRoute: () => WorkspaceMcpSessionsLayoutRoute,
  } as any)
const WorkspaceMcpSessionsAuthFailedLayoutRoute =
  WorkspaceMcpSessionsAuthFailedLayoutRouteImport.update({
    id: '/auth-failed',
    path: '/auth-failed',
    getParentRoute: () => WorkspaceMcpSessionsLayoutRoute,
  } as any)
const WorkspaceMcpSessionsAuthLayoutRoute =
  WorkspaceMcpSessionsAuthLayoutRouteImport.update({
    id: '/auth',
    path: '/auth',
    getParentRoute: () => WorkspaceMcpSessionsLayoutRoute,
  } as any)
const WorkspaceMcpRegistryOauthCallbackLayoutRoute =
  WorkspaceMcpRegistryOauthCallbackLayoutRouteImport.update({
    id: '/oauth-callback',
    path: '/oauth-callback',
    getParentRoute: () => WorkspaceMcpRegistryLayoutRoute,
  } as any)
const WorkspaceMcpRegistryLibraryLayoutRoute =
  WorkspaceMcpRegistryLibraryLayoutRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => WorkspaceMcpRegistryLayoutRoute,
  } as any)
const WorkspaceLogsMcpLogsLayoutRoute =
  WorkspaceLogsMcpLogsLayoutRouteImport.update({
    id: '/mcp-logs',
    path: '/mcp-logs',
    getParentRoute: () => WorkspaceLogsLayoutRoute,
  } as any)
const WorkspaceLogsConnectorsLayoutRoute =
  WorkspaceLogsConnectorsLayoutRouteImport.update({
    id: '/connectors',
    path: '/connectors',
    getParentRoute: () => WorkspaceLogsLayoutRoute,
  } as any)
const WorkspaceGuardrailsProvidersLayoutRoute =
  WorkspaceGuardrailsProvidersLayoutRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => WorkspaceGuardrailsLayoutRoute,
  } as any)
const WorkspaceGuardrailsConfigurationLayoutRoute =
  WorkspaceGuardrailsConfigurationLayoutRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => WorkspaceGuardrailsLayoutRoute,
  } as any)
const WorkspaceGovernanceVirtualKeysLayoutRoute =
  WorkspaceGovernanceVirtualKeysLayoutRouteImport.update({
    id: '/virtual-keys',
    path: '/virtual-keys',
    getParentRoute: () => WorkspaceGovernanceLayoutRoute,
  } as any)
const WorkspaceGovernanceUsersLayoutRoute =
  WorkspaceGovernanceUsersLayoutRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => WorkspaceGovernanceLayoutRoute,
  } as any)
const WorkspaceGovernanceTeamsLayoutRoute =
  WorkspaceGovernanceTeamsLayoutRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => WorkspaceGovernanceLayoutRoute,
  } as any)
const WorkspaceGovernanceRbacLayoutRoute =
  WorkspaceGovernanceRbacLayoutRouteImport.update({
    id: '/rbac',
    path: '/rbac',
    getParentRoute: () => WorkspaceGovernanceLayoutRoute,
  } as any)
const WorkspaceGovernanceCustomersLayoutRoute =
  WorkspaceGovernanceCustomersLayoutRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => WorkspaceGovernanceLayoutRoute,
  } as any)
const WorkspaceGovernanceBusinessUnitsLayoutRoute =
  WorkspaceGovernanceBusinessUnitsLayoutRouteImport.update({
    id: '/business-units',
    path: '/business-units',
    getParentRoute: () => WorkspaceGovernanceLayoutRoute,
  } as any)
const WorkspaceGovernanceAccessProfilesLayoutRoute =
  WorkspaceGovernanceAccessProfilesLayoutRouteImport.update({
    id: '/access-profiles',
    path: '/access-profiles',
    getParentRoute: () => WorkspaceGovernanceLayoutRoute,
  } as any)
const WorkspaceCustomPricingOverridesLayoutRoute =
  WorkspaceCustomPricingOverridesLayoutRouteImport.update({
    id: '/overrides',
    path: '/overrides',
    getParentRoute: () => WorkspaceCustomPricingLayoutRoute,
  } as any)
const WorkspaceConfigSecurityLayoutRoute =
  WorkspaceConfigSecurityLayoutRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => WorkspaceConfigLayoutRoute,
  } as any)
const WorkspaceConfigProxyLayoutRoute =
  WorkspaceConfigProxyLayoutRouteImport.update({
    id: '/proxy',
    path: '/proxy',
    getParentRoute: () => WorkspaceConfigLayoutRoute,
  } as any)
const WorkspaceConfigPricingConfigLayoutRoute =
  WorkspaceConfigPricingConfigLayoutRouteImport.update({
    id: '/pricing-config',
    path: '/pricing-config',
    getParentRoute: () => WorkspaceConfigLayoutRoute,
  } as any)
const WorkspaceConfigPerformanceTuningLayoutRoute =
  WorkspaceConfigPerformanceTuningLayoutRouteImport.update({
    id: '/performance-tuning',
    path: '/performance-tuning',
    getParentRoute: () => WorkspaceConfigLayoutRoute,
  } as any)
const WorkspaceConfigObservabilityLayoutRoute =
  WorkspaceConfigObservabilityLayoutRouteImport.update({
    id: '/observability',
    path: '/observability',
    getParentRoute: () => WorkspaceConfigLayoutRoute,
  } as any)
const WorkspaceConfigMcpGatewayLayoutRoute =
  WorkspaceConfigMcpGatewayLayoutRouteImport.update({
    id: '/mcp-gateway',
    path: '/mcp-gateway',
    getParentRoute: () => WorkspaceConfigLayoutRoute,
  } as any)
const WorkspaceConfigLoggingLayoutRoute =
  WorkspaceConfigLoggingLayoutRouteImport.update({
    id: '/logging',
    path: '/logging',
    getParentRoute: () => WorkspaceConfigLayoutRoute,
  } as any)
const WorkspaceConfigLargePayloadLayoutRoute =
  WorkspaceConfigLargePayloadLayoutRouteImport.update({
    id: '/large-payload',
    path: '/large-payload',
    getParentRoute: () => WorkspaceConfigLayoutRoute,
  } as any)
const WorkspaceConfigFeatureFlagsLayoutRoute =
  WorkspaceConfigFeatureFlagsLayoutRouteImport.update({
    id: '/feature-flags',
    path: '/feature-flags',
    getParentRoute: () => WorkspaceConfigLayoutRoute,
  } as any)
const WorkspaceConfigCompatibilityLayoutRoute =
  WorkspaceConfigCompatibilityLayoutRouteImport.update({
    id: '/compatibility',
    path: '/compatibility',
    getParentRoute: () => WorkspaceConfigLayoutRoute,
  } as any)
const WorkspaceConfigClientSettingsLayoutRoute =
  WorkspaceConfigClientSettingsLayoutRouteImport.update({
    id: '/client-settings',
    path: '/client-settings',
    getParentRoute: () => WorkspaceConfigLayoutRoute,
  } as any)
const WorkspaceConfigCachingLayoutRoute =
  WorkspaceConfigCachingLayoutRouteImport.update({
    id: '/caching',
    path: '/caching',
    getParentRoute: () => WorkspaceConfigLayoutRoute,
  } as any)
const WorkspaceConfigApiKeysLayoutRoute =
  WorkspaceConfigApiKeysLayoutRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => WorkspaceConfigLayoutRoute,
  } as any)
const WorkspaceAdaptiveRoutingSettingsLayoutRoute =
  WorkspaceAdaptiveRoutingSettingsLayoutRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorkspaceAdaptiveRoutingLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLayoutRoute
  '/login': typeof LoginLayoutRoute
  '/pprof': typeof PprofLayoutRoute
  '/signup': typeof SignupLayoutRoute
  '/workspace': typeof WorkspaceLayoutRouteWithChildren
  '/oauth/consent': typeof OauthConsentLayoutRoute
  '/workspace/adaptive-routing': typeof WorkspaceAdaptiveRoutingLayoutRouteWithChildren
  '/workspace/alert-channels': typeof WorkspaceAlertChannelsLayoutRoute
  '/workspace/audit-logs': typeof WorkspaceAuditLogsLayoutRoute
  '/workspace/browser-ai': typeof WorkspaceBrowserAiLayoutRoute
  '/workspace/circuit-breaker': typeof WorkspaceCircuitBreakerLayoutRoute
  '/workspace/cluster': typeof WorkspaceClusterLayoutRoute
  '/workspace/complexity-router': typeof WorkspaceComplexityRouterLayoutRoute
  '/workspace/config': typeof WorkspaceConfigLayoutRouteWithChildren
  '/workspace/custom-pricing': typeof WorkspaceCustomPricingLayoutRouteWithChildren
  '/workspace/dashboard': typeof WorkspaceDashboardLayoutRoute
  '/workspace/docs': typeof WorkspaceDocsLayoutRoute
  '/workspace/governance': typeof WorkspaceGovernanceLayoutRouteWithChildren
  '/workspace/guardrails': typeof WorkspaceGuardrailsLayoutRouteWithChildren
  '/workspace/logs': typeof WorkspaceLogsLayoutRouteWithChildren
  '/workspace/mcp-auth-config': typeof WorkspaceMcpAuthConfigLayoutRoute
  '/workspace/mcp-gateway': typeof WorkspaceMcpGatewayLayoutRoute
  '/workspace/mcp-logs': typeof WorkspaceMcpLogsLayoutRoute
  '/workspace/mcp-registry': typeof WorkspaceMcpRegistryLayoutRouteWithChildren
  '/workspace/mcp-sessions': typeof WorkspaceMcpSessionsLayoutRouteWithChildren
  '/workspace/mcp-settings': typeof WorkspaceMcpSettingsLayoutRoute
  '/workspace/mcp-tool-groups': typeof WorkspaceMcpToolGroupsLayoutRoute
  '/workspace/model-catalog': typeof WorkspaceModelCatalogLayoutRoute
  '/workspace/model-limits': typeof WorkspaceModelLimitsLayoutRoute
  '/workspace/oauth-grants': typeof WorkspaceOauthGrantsLayoutRoute
  '/workspace/observability': typeof WorkspaceObservabilityLayoutRoute
  '/workspace/plugins': typeof WorkspacePluginsLayoutRoute
  '/workspace/prompt-repo': typeof WorkspacePromptRepoLayoutRouteWithChildren
  '/workspace/providers': typeof WorkspaceProvidersLayoutRouteWithChildren
  '/workspace/rbac': typeof WorkspaceRbacLayoutRoute
  '/workspace/routing-rules': typeof WorkspaceRoutingRulesLayoutRouteWithChildren
  '/workspace/scim': typeof WorkspaceScimLayoutRouteWithChildren
  '/workspace/skills-repo': typeof WorkspaceSkillsRepoLayoutRoute
  '/workspace/virtual-keys': typeof WorkspaceVirtualKeysLayoutRoute
  '/workspace/adaptive-routing/settings': typeof WorkspaceAdaptiveRoutingSettingsLayoutRoute
  '/workspace/config/api-keys': typeof WorkspaceConfigApiKeysLayoutRoute
  '/workspace/config/caching': typeof WorkspaceConfigCachingLayoutRoute
  '/workspace/config/client-settings': typeof WorkspaceConfigClientSettingsLayoutRoute
  '/workspace/config/compatibility': typeof WorkspaceConfigCompatibilityLayoutRoute
  '/workspace/config/feature-flags': typeof WorkspaceConfigFeatureFlagsLayoutRoute
  '/workspace/config/large-payload': typeof WorkspaceConfigLargePayloadLayoutRoute
  '/workspace/config/logging': typeof WorkspaceConfigLoggingLayoutRoute
  '/workspace/config/mcp-gateway': typeof WorkspaceConfigMcpGatewayLayoutRoute
  '/workspace/config/observability': typeof WorkspaceConfigObservabilityLayoutRoute
  '/workspace/config/performance-tuning': typeof WorkspaceConfigPerformanceTuningLayoutRoute
  '/workspace/config/pricing-config': typeof WorkspaceConfigPricingConfigLayoutRoute
  '/workspace/config/proxy': typeof WorkspaceConfigProxyLayoutRoute
  '/workspace/config/security': typeof WorkspaceConfigSecurityLayoutRoute
  '/workspace/custom-pricing/overrides': typeof WorkspaceCustomPricingOverridesLayoutRoute
  '/workspace/governance/access-profiles': typeof WorkspaceGovernanceAccessProfilesLayoutRoute
  '/workspace/governance/business-units': typeof WorkspaceGovernanceBusinessUnitsLayoutRoute
  '/workspace/governance/customers': typeof WorkspaceGovernanceCustomersLayoutRoute
  '/workspace/governance/rbac': typeof WorkspaceGovernanceRbacLayoutRoute
  '/workspace/governance/teams': typeof WorkspaceGovernanceTeamsLayoutRoute
  '/workspace/governance/users': typeof WorkspaceGovernanceUsersLayoutRoute
  '/workspace/governance/virtual-keys': typeof WorkspaceGovernanceVirtualKeysLayoutRoute
  '/workspace/guardrails/configuration': typeof WorkspaceGuardrailsConfigurationLayoutRoute
  '/workspace/guardrails/providers': typeof WorkspaceGuardrailsProvidersLayoutRoute
  '/workspace/logs/connectors': typeof WorkspaceLogsConnectorsLayoutRoute
  '/workspace/logs/mcp-logs': typeof WorkspaceLogsMcpLogsLayoutRoute
  '/workspace/mcp-registry/library': typeof WorkspaceMcpRegistryLibraryLayoutRoute
  '/workspace/mcp-registry/oauth-callback': typeof WorkspaceMcpRegistryOauthCallbackLayoutRoute
  '/workspace/mcp-sessions/auth': typeof WorkspaceMcpSessionsAuthLayoutRoute
  '/workspace/mcp-sessions/auth-failed': typeof WorkspaceMcpSessionsAuthFailedLayoutRoute
  '/workspace/mcp-sessions/auth-success': typeof WorkspaceMcpSessionsAuthSuccessLayoutRoute
  '/workspace/prompt-repo/prompts': typeof WorkspacePromptRepoPromptsLayoutRoute
  '/workspace/providers/model-limits': typeof WorkspaceProvidersModelLimitsLayoutRoute
  '/workspace/providers/routing-rules': typeof WorkspaceProvidersRoutingRulesLayoutRoute
  '/workspace/routing-rules/tree': typeof WorkspaceRoutingRulesTreeLayoutRoute
  '/workspace/scim/oauth-discover-callback': typeof WorkspaceScimOauthDiscoverCallbackLayoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLayoutRoute
  '/login': typeof LoginLayoutRoute
  '/pprof': typeof PprofLayoutRoute
  '/signup': typeof SignupLayoutRoute
  '/workspace': typeof WorkspaceLayoutRouteWithChildren
  '/oauth/consent': typeof OauthConsentLayoutRoute
  '/workspace/adaptive-routing': typeof WorkspaceAdaptiveRoutingLayoutRouteWithChildren
  '/workspace/alert-channels': typeof WorkspaceAlertChannelsLayoutRoute
  '/workspace/audit-logs': typeof WorkspaceAuditLogsLayoutRoute
  '/workspace/browser-ai': typeof WorkspaceBrowserAiLayoutRoute
  '/workspace/circuit-breaker': typeof WorkspaceCircuitBreakerLayoutRoute
  '/workspace/cluster': typeof WorkspaceClusterLayoutRoute
  '/workspace/complexity-router': typeof WorkspaceComplexityRouterLayoutRoute
  '/workspace/config': typeof WorkspaceConfigLayoutRouteWithChildren
  '/workspace/custom-pricing': typeof WorkspaceCustomPricingLayoutRouteWithChildren
  '/workspace/dashboard': typeof WorkspaceDashboardLayoutRoute
  '/workspace/docs': typeof WorkspaceDocsLayoutRoute
  '/workspace/governance': typeof WorkspaceGovernanceLayoutRouteWithChildren
  '/workspace/guardrails': typeof WorkspaceGuardrailsLayoutRouteWithChildren
  '/workspace/logs': typeof WorkspaceLogsLayoutRouteWithChildren
  '/workspace/mcp-auth-config': typeof WorkspaceMcpAuthConfigLayoutRoute
  '/workspace/mcp-gateway': typeof WorkspaceMcpGatewayLayoutRoute
  '/workspace/mcp-logs': typeof WorkspaceMcpLogsLayoutRoute
  '/workspace/mcp-registry': typeof WorkspaceMcpRegistryLayoutRouteWithChildren
  '/workspace/mcp-sessions': typeof WorkspaceMcpSessionsLayoutRouteWithChildren
  '/workspace/mcp-settings': typeof WorkspaceMcpSettingsLayoutRoute
  '/workspace/mcp-tool-groups': typeof WorkspaceMcpToolGroupsLayoutRoute
  '/workspace/model-catalog': typeof WorkspaceModelCatalogLayoutRoute
  '/workspace/model-limits': typeof WorkspaceModelLimitsLayoutRoute
  '/workspace/oauth-grants': typeof WorkspaceOauthGrantsLayoutRoute
  '/workspace/observability': typeof WorkspaceObservabilityLayoutRoute
  '/workspace/plugins': typeof WorkspacePluginsLayoutRoute
  '/workspace/prompt-repo': typeof WorkspacePromptRepoLayoutRouteWithChildren
  '/workspace/providers': typeof WorkspaceProvidersLayoutRouteWithChildren
  '/workspace/rbac': typeof WorkspaceRbacLayoutRoute
  '/workspace/routing-rules': typeof WorkspaceRoutingRulesLayoutRouteWithChildren
  '/workspace/scim': typeof WorkspaceScimLayoutRouteWithChildren
  '/workspace/skills-repo': typeof WorkspaceSkillsRepoLayoutRoute
  '/workspace/virtual-keys': typeof WorkspaceVirtualKeysLayoutRoute
  '/workspace/adaptive-routing/settings': typeof WorkspaceAdaptiveRoutingSettingsLayoutRoute
  '/workspace/config/api-keys': typeof WorkspaceConfigApiKeysLayoutRoute
  '/workspace/config/caching': typeof WorkspaceConfigCachingLayoutRoute
  '/workspace/config/client-settings': typeof WorkspaceConfigClientSettingsLayoutRoute
  '/workspace/config/compatibility': typeof WorkspaceConfigCompatibilityLayoutRoute
  '/workspace/config/feature-flags': typeof WorkspaceConfigFeatureFlagsLayoutRoute
  '/workspace/config/large-payload': typeof WorkspaceConfigLargePayloadLayoutRoute
  '/workspace/config/logging': typeof WorkspaceConfigLoggingLayoutRoute
  '/workspace/config/mcp-gateway': typeof WorkspaceConfigMcpGatewayLayoutRoute
  '/workspace/config/observability': typeof WorkspaceConfigObservabilityLayoutRoute
  '/workspace/config/performance-tuning': typeof WorkspaceConfigPerformanceTuningLayoutRoute
  '/workspace/config/pricing-config': typeof WorkspaceConfigPricingConfigLayoutRoute
  '/workspace/config/proxy': typeof WorkspaceConfigProxyLayoutRoute
  '/workspace/config/security': typeof WorkspaceConfigSecurityLayoutRoute
  '/workspace/custom-pricing/overrides': typeof WorkspaceCustomPricingOverridesLayoutRoute
  '/workspace/governance/access-profiles': typeof WorkspaceGovernanceAccessProfilesLayoutRoute
  '/workspace/governance/business-units': typeof WorkspaceGovernanceBusinessUnitsLayoutRoute
  '/workspace/governance/customers': typeof WorkspaceGovernanceCustomersLayoutRoute
  '/workspace/governance/rbac': typeof WorkspaceGovernanceRbacLayoutRoute
  '/workspace/governance/teams': typeof WorkspaceGovernanceTeamsLayoutRoute
  '/workspace/governance/users': typeof WorkspaceGovernanceUsersLayoutRoute
  '/workspace/governance/virtual-keys': typeof WorkspaceGovernanceVirtualKeysLayoutRoute
  '/workspace/guardrails/configuration': typeof WorkspaceGuardrailsConfigurationLayoutRoute
  '/workspace/guardrails/providers': typeof WorkspaceGuardrailsProvidersLayoutRoute
  '/workspace/logs/connectors': typeof WorkspaceLogsConnectorsLayoutRoute
  '/workspace/logs/mcp-logs': typeof WorkspaceLogsMcpLogsLayoutRoute
  '/workspace/mcp-registry/library': typeof WorkspaceMcpRegistryLibraryLayoutRoute
  '/workspace/mcp-registry/oauth-callback': typeof WorkspaceMcpRegistryOauthCallbackLayoutRoute
  '/workspace/mcp-sessions/auth': typeof WorkspaceMcpSessionsAuthLayoutRoute
  '/workspace/mcp-sessions/auth-failed': typeof WorkspaceMcpSessionsAuthFailedLayoutRoute
  '/workspace/mcp-sessions/auth-success': typeof WorkspaceMcpSessionsAuthSuccessLayoutRoute
  '/workspace/prompt-repo/prompts': typeof WorkspacePromptRepoPromptsLayoutRoute
  '/workspace/providers/model-limits': typeof WorkspaceProvidersModelLimitsLayoutRoute
  '/workspace/providers/routing-rules': typeof WorkspaceProvidersRoutingRulesLayoutRoute
  '/workspace/routing-rules/tree': typeof WorkspaceRoutingRulesTreeLayoutRoute
  '/workspace/scim/oauth-discover-callback': typeof WorkspaceScimOauthDiscoverCallbackLayoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLayoutRoute
  '/login': typeof LoginLayoutRoute
  '/pprof': typeof PprofLayoutRoute
  '/signup': typeof SignupLayoutRoute
  '/workspace': typeof WorkspaceLayoutRouteWithChildren
  '/oauth/consent': typeof OauthConsentLayoutRoute
  '/workspace/adaptive-routing': typeof WorkspaceAdaptiveRoutingLayoutRouteWithChildren
  '/workspace/alert-channels': typeof WorkspaceAlertChannelsLayoutRoute
  '/workspace/audit-logs': typeof WorkspaceAuditLogsLayoutRoute
  '/workspace/browser-ai': typeof WorkspaceBrowserAiLayoutRoute
  '/workspace/circuit-breaker': typeof WorkspaceCircuitBreakerLayoutRoute
  '/workspace/cluster': typeof WorkspaceClusterLayoutRoute
  '/workspace/complexity-router': typeof WorkspaceComplexityRouterLayoutRoute
  '/workspace/config': typeof WorkspaceConfigLayoutRouteWithChildren
  '/workspace/custom-pricing': typeof WorkspaceCustomPricingLayoutRouteWithChildren
  '/workspace/dashboard': typeof WorkspaceDashboardLayoutRoute
  '/workspace/docs': typeof WorkspaceDocsLayoutRoute
  '/workspace/governance': typeof WorkspaceGovernanceLayoutRouteWithChildren
  '/workspace/guardrails': typeof WorkspaceGuardrailsLayoutRouteWithChildren
  '/workspace/logs': typeof WorkspaceLogsLayoutRouteWithChildren
  '/workspace/mcp-auth-config': typeof WorkspaceMcpAuthConfigLayoutRoute
  '/workspace/mcp-gateway': typeof WorkspaceMcpGatewayLayoutRoute
  '/workspace/mcp-logs': typeof WorkspaceMcpLogsLayoutRoute
  '/workspace/mcp-registry': typeof WorkspaceMcpRegistryLayoutRouteWithChildren
  '/workspace/mcp-sessions': typeof WorkspaceMcpSessionsLayoutRouteWithChildren
  '/workspace/mcp-settings': typeof WorkspaceMcpSettingsLayoutRoute
  '/workspace/mcp-tool-groups': typeof WorkspaceMcpToolGroupsLayoutRoute
  '/workspace/model-catalog': typeof WorkspaceModelCatalogLayoutRoute
  '/workspace/model-limits': typeof WorkspaceModelLimitsLayoutRoute
  '/workspace/oauth-grants': typeof WorkspaceOauthGrantsLayoutRoute
  '/workspace/observability': typeof WorkspaceObservabilityLayoutRoute
  '/workspace/plugins': typeof WorkspacePluginsLayoutRoute
  '/workspace/prompt-repo': typeof WorkspacePromptRepoLayoutRouteWithChildren
  '/workspace/providers': typeof WorkspaceProvidersLayoutRouteWithChildren
  '/workspace/rbac': typeof WorkspaceRbacLayoutRoute
  '/workspace/routing-rules': typeof WorkspaceRoutingRulesLayoutRouteWithChildren
  '/workspace/scim': typeof WorkspaceScimLayoutRouteWithChildren
  '/workspace/skills-repo': typeof WorkspaceSkillsRepoLayoutRoute
  '/workspace/virtual-keys': typeof WorkspaceVirtualKeysLayoutRoute
  '/workspace/adaptive-routing/settings': typeof WorkspaceAdaptiveRoutingSettingsLayoutRoute
  '/workspace/config/api-keys': typeof WorkspaceConfigApiKeysLayoutRoute
  '/workspace/config/caching': typeof WorkspaceConfigCachingLayoutRoute
  '/workspace/config/client-settings': typeof WorkspaceConfigClientSettingsLayoutRoute
  '/workspace/config/compatibility': typeof WorkspaceConfigCompatibilityLayoutRoute
  '/workspace/config/feature-flags': typeof WorkspaceConfigFeatureFlagsLayoutRoute
  '/workspace/config/large-payload': typeof WorkspaceConfigLargePayloadLayoutRoute
  '/workspace/config/logging': typeof WorkspaceConfigLoggingLayoutRoute
  '/workspace/config/mcp-gateway': typeof WorkspaceConfigMcpGatewayLayoutRoute
  '/workspace/config/observability': typeof WorkspaceConfigObservabilityLayoutRoute
  '/workspace/config/performance-tuning': typeof WorkspaceConfigPerformanceTuningLayoutRoute
  '/workspace/config/pricing-config': typeof WorkspaceConfigPricingConfigLayoutRoute
  '/workspace/config/proxy': typeof WorkspaceConfigProxyLayoutRoute
  '/workspace/config/security': typeof WorkspaceConfigSecurityLayoutRoute
  '/workspace/custom-pricing/overrides': typeof WorkspaceCustomPricingOverridesLayoutRoute
  '/workspace/governance/access-profiles': typeof WorkspaceGovernanceAccessProfilesLayoutRoute
  '/workspace/governance/business-units': typeof WorkspaceGovernanceBusinessUnitsLayoutRoute
  '/workspace/governance/customers': typeof WorkspaceGovernanceCustomersLayoutRoute
  '/workspace/governance/rbac': typeof WorkspaceGovernanceRbacLayoutRoute
  '/workspace/governance/teams': typeof WorkspaceGovernanceTeamsLayoutRoute
  '/workspace/governance/users': typeof WorkspaceGovernanceUsersLayoutRoute
  '/workspace/governance/virtual-keys': typeof WorkspaceGovernanceVirtualKeysLayoutRoute
  '/workspace/guardrails/configuration': typeof WorkspaceGuardrailsConfigurationLayoutRoute
  '/workspace/guardrails/providers': typeof WorkspaceGuardrailsProvidersLayoutRoute
  '/workspace/logs/connectors': typeof WorkspaceLogsConnectorsLayoutRoute
  '/workspace/logs/mcp-logs': typeof WorkspaceLogsMcpLogsLayoutRoute
  '/workspace/mcp-registry/library': typeof WorkspaceMcpRegistryLibraryLayoutRoute
  '/workspace/mcp-registry/oauth-callback': typeof WorkspaceMcpRegistryOauthCallbackLayoutRoute
  '/workspace/mcp-sessions/auth': typeof WorkspaceMcpSessionsAuthLayoutRoute
  '/workspace/mcp-sessions/auth-failed': typeof WorkspaceMcpSessionsAuthFailedLayoutRoute
  '/workspace/mcp-sessions/auth-success': typeof WorkspaceMcpSessionsAuthSuccessLayoutRoute
  '/workspace/prompt-repo/prompts': typeof WorkspacePromptRepoPromptsLayoutRoute
  '/workspace/providers/model-limits': typeof WorkspaceProvidersModelLimitsLayoutRoute
  '/workspace/providers/routing-rules': typeof WorkspaceProvidersRoutingRulesLayoutRoute
  '/workspace/routing-rules/tree': typeof WorkspaceRoutingRulesTreeLayoutRoute
  '/workspace/scim/oauth-discover-callback': typeof WorkspaceScimOauthDiscoverCallbackLayoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pprof'
    | '/signup'
    | '/workspace'
    | '/oauth/consent'
    | '/workspace/adaptive-routing'
    | '/workspace/alert-channels'
    | '/workspace/audit-logs'
    | '/workspace/browser-ai'
    | '/workspace/circuit-breaker'
    | '/workspace/cluster'
    | '/workspace/complexity-router'
    | '/workspace/config'
    | '/workspace/custom-pricing'
    | '/workspace/dashboard'
    | '/workspace/docs'
    | '/workspace/governance'
    | '/workspace/guardrails'
    | '/workspace/logs'
    | '/workspace/mcp-auth-config'
    | '/workspace/mcp-gateway'
    | '/workspace/mcp-logs'
    | '/workspace/mcp-registry'
    | '/workspace/mcp-sessions'
    | '/workspace/mcp-settings'
    | '/workspace/mcp-tool-groups'
    | '/workspace/model-catalog'
    | '/workspace/model-limits'
    | '/workspace/oauth-grants'
    | '/workspace/observability'
    | '/workspace/plugins'
    | '/workspace/prompt-repo'
    | '/workspace/providers'
    | '/workspace/rbac'
    | '/workspace/routing-rules'
    | '/workspace/scim'
    | '/workspace/skills-repo'
    | '/workspace/virtual-keys'
    | '/workspace/adaptive-routing/settings'
    | '/workspace/config/api-keys'
    | '/workspace/config/caching'
    | '/workspace/config/client-settings'
    | '/workspace/config/compatibility'
    | '/workspace/config/feature-flags'
    | '/workspace/config/large-payload'
    | '/workspace/config/logging'
    | '/workspace/config/mcp-gateway'
    | '/workspace/config/observability'
    | '/workspace/config/performance-tuning'
    | '/workspace/config/pricing-config'
    | '/workspace/config/proxy'
    | '/workspace/config/security'
    | '/workspace/custom-pricing/overrides'
    | '/workspace/governance/access-profiles'
    | '/workspace/governance/business-units'
    | '/workspace/governance/customers'
    | '/workspace/governance/rbac'
    | '/workspace/governance/teams'
    | '/workspace/governance/users'
    | '/workspace/governance/virtual-keys'
    | '/workspace/guardrails/configuration'
    | '/workspace/guardrails/providers'
    | '/workspace/logs/connectors'
    | '/workspace/logs/mcp-logs'
    | '/workspace/mcp-registry/library'
    | '/workspace/mcp-registry/oauth-callback'
    | '/workspace/mcp-sessions/auth'
    | '/workspace/mcp-sessions/auth-failed'
    | '/workspace/mcp-sessions/auth-success'
    | '/workspace/prompt-repo/prompts'
    | '/workspace/providers/model-limits'
    | '/workspace/providers/routing-rules'
    | '/workspace/routing-rules/tree'
    | '/workspace/scim/oauth-discover-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pprof'
    | '/signup'
    | '/workspace'
    | '/oauth/consent'
    | '/workspace/adaptive-routing'
    | '/workspace/alert-channels'
    | '/workspace/audit-logs'
    | '/workspace/browser-ai'
    | '/workspace/circuit-breaker'
    | '/workspace/cluster'
    | '/workspace/complexity-router'
    | '/workspace/config'
    | '/workspace/custom-pricing'
    | '/workspace/dashboard'
    | '/workspace/docs'
    | '/workspace/governance'
    | '/workspace/guardrails'
    | '/workspace/logs'
    | '/workspace/mcp-auth-config'
    | '/workspace/mcp-gateway'
    | '/workspace/mcp-logs'
    | '/workspace/mcp-registry'
    | '/workspace/mcp-sessions'
    | '/workspace/mcp-settings'
    | '/workspace/mcp-tool-groups'
    | '/workspace/model-catalog'
    | '/workspace/model-limits'
    | '/workspace/oauth-grants'
    | '/workspace/observability'
    | '/workspace/plugins'
    | '/workspace/prompt-repo'
    | '/workspace/providers'
    | '/workspace/rbac'
    | '/workspace/routing-rules'
    | '/workspace/scim'
    | '/workspace/skills-repo'
    | '/workspace/virtual-keys'
    | '/workspace/adaptive-routing/settings'
    | '/workspace/config/api-keys'
    | '/workspace/config/caching'
    | '/workspace/config/client-settings'
    | '/workspace/config/compatibility'
    | '/workspace/config/feature-flags'
    | '/workspace/config/large-payload'
    | '/workspace/config/logging'
    | '/workspace/config/mcp-gateway'
    | '/workspace/config/observability'
    | '/workspace/config/performance-tuning'
    | '/workspace/config/pricing-config'
    | '/workspace/config/proxy'
    | '/workspace/config/security'
    | '/workspace/custom-pricing/overrides'
    | '/workspace/governance/access-profiles'
    | '/workspace/governance/business-units'
    | '/workspace/governance/customers'
    | '/workspace/governance/rbac'
    | '/workspace/governance/teams'
    | '/workspace/governance/users'
    | '/workspace/governance/virtual-keys'
    | '/workspace/guardrails/configuration'
    | '/workspace/guardrails/providers'
    | '/workspace/logs/connectors'
    | '/workspace/logs/mcp-logs'
    | '/workspace/mcp-registry/library'
    | '/workspace/mcp-registry/oauth-callback'
    | '/workspace/mcp-sessions/auth'
    | '/workspace/mcp-sessions/auth-failed'
    | '/workspace/mcp-sessions/auth-success'
    | '/workspace/prompt-repo/prompts'
    | '/workspace/providers/model-limits'
    | '/workspace/providers/routing-rules'
    | '/workspace/routing-rules/tree'
    | '/workspace/scim/oauth-discover-callback'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/pprof'
    | '/signup'
    | '/workspace'
    | '/oauth/consent'
    | '/workspace/adaptive-routing'
    | '/workspace/alert-channels'
    | '/workspace/audit-logs'
    | '/workspace/browser-ai'
    | '/workspace/circuit-breaker'
    | '/workspace/cluster'
    | '/workspace/complexity-router'
    | '/workspace/config'
    | '/workspace/custom-pricing'
    | '/workspace/dashboard'
    | '/workspace/docs'
    | '/workspace/governance'
    | '/workspace/guardrails'
    | '/workspace/logs'
    | '/workspace/mcp-auth-config'
    | '/workspace/mcp-gateway'
    | '/workspace/mcp-logs'
    | '/workspace/mcp-registry'
    | '/workspace/mcp-sessions'
    | '/workspace/mcp-settings'
    | '/workspace/mcp-tool-groups'
    | '/workspace/model-catalog'
    | '/workspace/model-limits'
    | '/workspace/oauth-grants'
    | '/workspace/observability'
    | '/workspace/plugins'
    | '/workspace/prompt-repo'
    | '/workspace/providers'
    | '/workspace/rbac'
    | '/workspace/routing-rules'
    | '/workspace/scim'
    | '/workspace/skills-repo'
    | '/workspace/virtual-keys'
    | '/workspace/adaptive-routing/settings'
    | '/workspace/config/api-keys'
    | '/workspace/config/caching'
    | '/workspace/config/client-settings'
    | '/workspace/config/compatibility'
    | '/workspace/config/feature-flags'
    | '/workspace/config/large-payload'
    | '/workspace/config/logging'
    | '/workspace/config/mcp-gateway'
    | '/workspace/config/observability'
    | '/workspace/config/performance-tuning'
    | '/workspace/config/pricing-config'
    | '/workspace/config/proxy'
    | '/workspace/config/security'
    | '/workspace/custom-pricing/overrides'
    | '/workspace/governance/access-profiles'
    | '/workspace/governance/business-units'
    | '/workspace/governance/customers'
    | '/workspace/governance/rbac'
    | '/workspace/governance/teams'
    | '/workspace/governance/users'
    | '/workspace/governance/virtual-keys'
    | '/workspace/guardrails/configuration'
    | '/workspace/guardrails/providers'
    | '/workspace/logs/connectors'
    | '/workspace/logs/mcp-logs'
    | '/workspace/mcp-registry/library'
    | '/workspace/mcp-registry/oauth-callback'
    | '/workspace/mcp-sessions/auth'
    | '/workspace/mcp-sessions/auth-failed'
    | '/workspace/mcp-sessions/auth-success'
    | '/workspace/prompt-repo/prompts'
    | '/workspace/providers/model-limits'
    | '/workspace/providers/routing-rules'
    | '/workspace/routing-rules/tree'
    | '/workspace/scim/oauth-discover-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLayoutRoute: typeof IndexLayoutRoute
  LoginLayoutRoute: typeof LoginLayoutRoute
  PprofLayoutRoute: typeof PprofLayoutRoute
  SignupLayoutRoute: typeof SignupLayoutRoute
  WorkspaceLayoutRoute: typeof WorkspaceLayoutRouteWithChildren
  OauthConsentLayoutRoute: typeof OauthConsentLayoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pprof': {
      id: '/pprof'
      path: '/pprof'
      fullPath: '/pprof'
      preLoaderRoute: typeof PprofLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/virtual-keys': {
      id: '/workspace/virtual-keys'
      path: '/virtual-keys'
      fullPath: '/workspace/virtual-keys'
      preLoaderRoute: typeof WorkspaceVirtualKeysLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/skills-repo': {
      id: '/workspace/skills-repo'
      path: '/skills-repo'
      fullPath: '/workspace/skills-repo'
      preLoaderRoute: typeof WorkspaceSkillsRepoLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/scim': {
      id: '/workspace/scim'
      path: '/scim'
      fullPath: '/workspace/scim'
      preLoaderRoute: typeof WorkspaceScimLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/routing-rules': {
      id: '/workspace/routing-rules'
      path: '/routing-rules'
      fullPath: '/workspace/routing-rules'
      preLoaderRoute: typeof WorkspaceRoutingRulesLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/rbac': {
      id: '/workspace/rbac'
      path: '/rbac'
      fullPath: '/workspace/rbac'
      preLoaderRoute: typeof WorkspaceRbacLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/providers': {
      id: '/workspace/providers'
      path: '/providers'
      fullPath: '/workspace/providers'
      preLoaderRoute: typeof WorkspaceProvidersLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/prompt-repo': {
      id: '/workspace/prompt-repo'
      path: '/prompt-repo'
      fullPath: '/workspace/prompt-repo'
      preLoaderRoute: typeof WorkspacePromptRepoLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/plugins': {
      id: '/workspace/plugins'
      path: '/plugins'
      fullPath: '/workspace/plugins'
      preLoaderRoute: typeof WorkspacePluginsLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/observability': {
      id: '/workspace/observability'
      path: '/observability'
      fullPath: '/workspace/observability'
      preLoaderRoute: typeof WorkspaceObservabilityLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/oauth-grants': {
      id: '/workspace/oauth-grants'
      path: '/oauth-grants'
      fullPath: '/workspace/oauth-grants'
      preLoaderRoute: typeof WorkspaceOauthGrantsLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/model-limits': {
      id: '/workspace/model-limits'
      path: '/model-limits'
      fullPath: '/workspace/model-limits'
      preLoaderRoute: typeof WorkspaceModelLimitsLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/model-catalog': {
      id: '/workspace/model-catalog'
      path: '/model-catalog'
      fullPath: '/workspace/model-catalog'
      preLoaderRoute: typeof WorkspaceModelCatalogLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/mcp-tool-groups': {
      id: '/workspace/mcp-tool-groups'
      path: '/mcp-tool-groups'
      fullPath: '/workspace/mcp-tool-groups'
      preLoaderRoute: typeof WorkspaceMcpToolGroupsLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/mcp-settings': {
      id: '/workspace/mcp-settings'
      path: '/mcp-settings'
      fullPath: '/workspace/mcp-settings'
      preLoaderRoute: typeof WorkspaceMcpSettingsLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/mcp-sessions': {
      id: '/workspace/mcp-sessions'
      path: '/mcp-sessions'
      fullPath: '/workspace/mcp-sessions'
      preLoaderRoute: typeof WorkspaceMcpSessionsLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/mcp-registry': {
      id: '/workspace/mcp-registry'
      path: '/mcp-registry'
      fullPath: '/workspace/mcp-registry'
      preLoaderRoute: typeof WorkspaceMcpRegistryLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/mcp-logs': {
      id: '/workspace/mcp-logs'
      path: '/mcp-logs'
      fullPath: '/workspace/mcp-logs'
      preLoaderRoute: typeof WorkspaceMcpLogsLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/mcp-gateway': {
      id: '/workspace/mcp-gateway'
      path: '/mcp-gateway'
      fullPath: '/workspace/mcp-gateway'
      preLoaderRoute: typeof WorkspaceMcpGatewayLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/mcp-auth-config': {
      id: '/workspace/mcp-auth-config'
      path: '/mcp-auth-config'
      fullPath: '/workspace/mcp-auth-config'
      preLoaderRoute: typeof WorkspaceMcpAuthConfigLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/logs': {
      id: '/workspace/logs'
      path: '/logs'
      fullPath: '/workspace/logs'
      preLoaderRoute: typeof WorkspaceLogsLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/guardrails': {
      id: '/workspace/guardrails'
      path: '/guardrails'
      fullPath: '/workspace/guardrails'
      preLoaderRoute: typeof WorkspaceGuardrailsLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/governance': {
      id: '/workspace/governance'
      path: '/governance'
      fullPath: '/workspace/governance'
      preLoaderRoute: typeof WorkspaceGovernanceLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/docs': {
      id: '/workspace/docs'
      path: '/docs'
      fullPath: '/workspace/docs'
      preLoaderRoute: typeof WorkspaceDocsLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/dashboard': {
      id: '/workspace/dashboard'
      path: '/dashboard'
      fullPath: '/workspace/dashboard'
      preLoaderRoute: typeof WorkspaceDashboardLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/custom-pricing': {
      id: '/workspace/custom-pricing'
      path: '/custom-pricing'
      fullPath: '/workspace/custom-pricing'
      preLoaderRoute: typeof WorkspaceCustomPricingLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/config': {
      id: '/workspace/config'
      path: '/config'
      fullPath: '/workspace/config'
      preLoaderRoute: typeof WorkspaceConfigLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/complexity-router': {
      id: '/workspace/complexity-router'
      path: '/complexity-router'
      fullPath: '/workspace/complexity-router'
      preLoaderRoute: typeof WorkspaceComplexityRouterLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/cluster': {
      id: '/workspace/cluster'
      path: '/cluster'
      fullPath: '/workspace/cluster'
      preLoaderRoute: typeof WorkspaceClusterLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/circuit-breaker': {
      id: '/workspace/circuit-breaker'
      path: '/circuit-breaker'
      fullPath: '/workspace/circuit-breaker'
      preLoaderRoute: typeof WorkspaceCircuitBreakerLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/browser-ai': {
      id: '/workspace/browser-ai'
      path: '/browser-ai'
      fullPath: '/workspace/browser-ai'
      preLoaderRoute: typeof WorkspaceBrowserAiLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/audit-logs': {
      id: '/workspace/audit-logs'
      path: '/audit-logs'
      fullPath: '/workspace/audit-logs'
      preLoaderRoute: typeof WorkspaceAuditLogsLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/alert-channels': {
      id: '/workspace/alert-channels'
      path: '/alert-channels'
      fullPath: '/workspace/alert-channels'
      preLoaderRoute: typeof WorkspaceAlertChannelsLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/workspace/adaptive-routing': {
      id: '/workspace/adaptive-routing'
      path: '/adaptive-routing'
      fullPath: '/workspace/adaptive-routing'
      preLoaderRoute: typeof WorkspaceAdaptiveRoutingLayoutRouteImport
      parentRoute: typeof WorkspaceLayoutRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/scim/oauth-discover-callback': {
      id: '/workspace/scim/oauth-discover-callback'
      path: '/oauth-discover-callback'
      fullPath: '/workspace/scim/oauth-discover-callback'
      preLoaderRoute: typeof WorkspaceScimOauthDiscoverCallbackLayoutRouteImport
      parentRoute: typeof WorkspaceScimLayoutRoute
    }
    '/workspace/routing-rules/tree': {
      id: '/workspace/routing-rules/tree'
      path: '/tree'
      fullPath: '/workspace/routing-rules/tree'
      preLoaderRoute: typeof WorkspaceRoutingRulesTreeLayoutRouteImport
      parentRoute: typeof WorkspaceRoutingRulesLayoutRoute
    }
    '/workspace/providers/routing-rules': {
      id: '/workspace/providers/routing-rules'
      path: '/routing-rules'
      fullPath: '/workspace/providers/routing-rules'
      preLoaderRoute: typeof WorkspaceProvidersRoutingRulesLayoutRouteImport
      parentRoute: typeof WorkspaceProvidersLayoutRoute
    }
    '/workspace/providers/model-limits': {
      id: '/workspace/providers/model-limits'
      path: '/model-limits'
      fullPath: '/workspace/providers/model-limits'
      preLoaderRoute: typeof WorkspaceProvidersModelLimitsLayoutRouteImport
      parentRoute: typeof WorkspaceProvidersLayoutRoute
    }
    '/workspace/prompt-repo/prompts': {
      id: '/workspace/prompt-repo/prompts'
      path: '/prompts'
      fullPath: '/workspace/prompt-repo/prompts'
      preLoaderRoute: typeof WorkspacePromptRepoPromptsLayoutRouteImport
      parentRoute: typeof WorkspacePromptRepoLayoutRoute
    }
    '/workspace/mcp-sessions/auth-success': {
      id: '/workspace/mcp-sessions/auth-success'
      path: '/auth-success'
      fullPath: '/workspace/mcp-sessions/auth-success'
      preLoaderRoute: typeof WorkspaceMcpSessionsAuthSuccessLayoutRouteImport
      parentRoute: typeof WorkspaceMcpSessionsLayoutRoute
    }
    '/workspace/mcp-sessions/auth-failed': {
      id: '/workspace/mcp-sessions/auth-failed'
      path: '/auth-failed'
      fullPath: '/workspace/mcp-sessions/auth-failed'
      preLoaderRoute: typeof WorkspaceMcpSessionsAuthFailedLayoutRouteImport
      parentRoute: typeof WorkspaceMcpSessionsLayoutRoute
    }
    '/workspace/mcp-sessions/auth': {
      id: '/workspace/mcp-sessions/auth'
      path: '/auth'
      fullPath: '/workspace/mcp-sessions/auth'
      preLoaderRoute: typeof WorkspaceMcpSessionsAuthLayoutRouteImport
      parentRoute: typeof WorkspaceMcpSessionsLayoutRoute
    }
    '/workspace/mcp-registry/oauth-callback': {
      id: '/workspace/mcp-registry/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/workspace/mcp-registry/oauth-callback'
      preLoaderRoute: typeof WorkspaceMcpRegistryOauthCallbackLayoutRouteImport
      parentRoute: typeof WorkspaceMcpRegistryLayoutRoute
    }
    '/workspace/mcp-registry/library': {
      id: '/workspace/mcp-registry/library'
      path: '/library'
      fullPath: '/workspace/mcp-registry/library'
      preLoaderRoute: typeof WorkspaceMcpRegistryLibraryLayoutRouteImport
      parentRoute: typeof WorkspaceMcpRegistryLayoutRoute
    }
    '/workspace/logs/mcp-logs': {
      id: '/workspace/logs/mcp-logs'
      path: '/mcp-logs'
      fullPath: '/workspace/logs/mcp-logs'
      preLoaderRoute: typeof WorkspaceLogsMcpLogsLayoutRouteImport
      parentRoute: typeof WorkspaceLogsLayoutRoute
    }
    '/workspace/logs/connectors': {
      id: '/workspace/logs/connectors'
      path: '/connectors'
      fullPath: '/workspace/logs/connectors'
      preLoaderRoute: typeof WorkspaceLogsConnectorsLayoutRouteImport
      parentRoute: typeof WorkspaceLogsLayoutRoute
    }
    '/workspace/guardrails/providers': {
      id: '/workspace/guardrails/providers'
      path: '/providers'
      fullPath: '/workspace/guardrails/providers'
      preLoaderRoute: typeof WorkspaceGuardrailsProvidersLayoutRouteImport
      parentRoute: typeof WorkspaceGuardrailsLayoutRoute
    }
    '/workspace/guardrails/configuration': {
      id: '/workspace/guardrails/configuration'
      path: '/configuration'
      fullPath: '/workspace/guardrails/configuration'
      preLoaderRoute: typeof WorkspaceGuardrailsConfigurationLayoutRouteImport
      parentRoute: typeof WorkspaceGuardrailsLayoutRoute
    }
    '/workspace/governance/virtual-keys': {
      id: '/workspace/governance/virtual-keys'
      path: '/virtual-keys'
      fullPath: '/workspace/governance/virtual-keys'
      preLoaderRoute: typeof WorkspaceGovernanceVirtualKeysLayoutRouteImport
      parentRoute: typeof WorkspaceGovernanceLayoutRoute
    }
    '/workspace/governance/users': {
      id: '/workspace/governance/users'
      path: '/users'
      fullPath: '/workspace/governance/users'
      preLoaderRoute: typeof WorkspaceGovernanceUsersLayoutRouteImport
      parentRoute: typeof WorkspaceGovernanceLayoutRoute
    }
    '/workspace/governance/teams': {
      id: '/workspace/governance/teams'
      path: '/teams'
      fullPath: '/workspace/governance/teams'
      preLoaderRoute: typeof WorkspaceGovernanceTeamsLayoutRouteImport
      parentRoute: typeof WorkspaceGovernanceLayoutRoute
    }
    '/workspace/governance/rbac': {
      id: '/workspace/governance/rbac'
      path: '/rbac'
      fullPath: '/workspace/governance/rbac'
      preLoaderRoute: typeof WorkspaceGovernanceRbacLayoutRouteImport
      parentRoute: typeof WorkspaceGovernanceLayoutRoute
    }
    '/workspace/governance/customers': {
      id: '/workspace/governance/customers'
      path: '/customers'
      fullPath: '/workspace/governance/customers'
      preLoaderRoute: typeof WorkspaceGovernanceCustomersLayoutRouteImport
      parentRoute: typeof WorkspaceGovernanceLayoutRoute
    }
    '/workspace/governance/business-units': {
      id: '/workspace/governance/business-units'
      path: '/business-units'
      fullPath: '/workspace/governance/business-units'
      preLoaderRoute: typeof WorkspaceGovernanceBusinessUnitsLayoutRouteImport
      parentRoute: typeof WorkspaceGovernanceLayoutRoute
    }
    '/workspace/governance/access-profiles': {
      id: '/workspace/governance/access-profiles'
      path: '/access-profiles'
      fullPath: '/workspace/governance/access-profiles'
      preLoaderRoute: typeof WorkspaceGovernanceAccessProfilesLayoutRouteImport
      parentRoute: typeof WorkspaceGovernanceLayoutRoute
    }
    '/workspace/custom-pricing/overrides': {
      id: '/workspace/custom-pricing/overrides'
      path: '/overrides'
      fullPath: '/workspace/custom-pricing/overrides'
      preLoaderRoute: typeof WorkspaceCustomPricingOverridesLayoutRouteImport
      parentRoute: typeof WorkspaceCustomPricingLayoutRoute
    }
    '/workspace/config/security': {
      id: '/workspace/config/security'
      path: '/security'
      fullPath: '/workspace/config/security'
      preLoaderRoute: typeof WorkspaceConfigSecurityLayoutRouteImport
      parentRoute: typeof WorkspaceConfigLayoutRoute
    }
    '/workspace/config/proxy': {
      id: '/workspace/config/proxy'
      path: '/proxy'
      fullPath: '/workspace/config/proxy'
      preLoaderRoute: typeof WorkspaceConfigProxyLayoutRouteImport
      parentRoute: typeof WorkspaceConfigLayoutRoute
    }
    '/workspace/config/pricing-config': {
      id: '/workspace/config/pricing-config'
      path: '/pricing-config'
      fullPath: '/workspace/config/pricing-config'
      preLoaderRoute: typeof WorkspaceConfigPricingConfigLayoutRouteImport
      parentRoute: typeof WorkspaceConfigLayoutRoute
    }
    '/workspace/config/performance-tuning': {
      id: '/workspace/config/performance-tuning'
      path: '/performance-tuning'
      fullPath: '/workspace/config/performance-tuning'
      preLoaderRoute: typeof WorkspaceConfigPerformanceTuningLayoutRouteImport
      parentRoute: typeof WorkspaceConfigLayoutRoute
    }
    '/workspace/config/observability': {
      id: '/workspace/config/observability'
      path: '/observability'
      fullPath: '/workspace/config/observability'
      preLoaderRoute: typeof WorkspaceConfigObservabilityLayoutRouteImport
      parentRoute: typeof WorkspaceConfigLayoutRoute
    }
    '/workspace/config/mcp-gateway': {
      id: '/workspace/config/mcp-gateway'
      path: '/mcp-gateway'
      fullPath: '/workspace/config/mcp-gateway'
      preLoaderRoute: typeof WorkspaceConfigMcpGatewayLayoutRouteImport
      parentRoute: typeof WorkspaceConfigLayoutRoute
    }
    '/workspace/config/logging': {
      id: '/workspace/config/logging'
      path: '/logging'
      fullPath: '/workspace/config/logging'
      preLoaderRoute: typeof WorkspaceConfigLoggingLayoutRouteImport
      parentRoute: typeof WorkspaceConfigLayoutRoute
    }
    '/workspace/config/large-payload': {
      id: '/workspace/config/large-payload'
      path: '/large-payload'
      fullPath: '/workspace/config/large-payload'
      preLoaderRoute: typeof WorkspaceConfigLargePayloadLayoutRouteImport
      parentRoute: typeof WorkspaceConfigLayoutRoute
    }
    '/workspace/config/feature-flags': {
      id: '/workspace/config/feature-flags'
      path: '/feature-flags'
      fullPath: '/workspace/config/feature-flags'
      preLoaderRoute: typeof WorkspaceConfigFeatureFlagsLayoutRouteImport
      parentRoute: typeof WorkspaceConfigLayoutRoute
    }
    '/workspace/config/compatibility': {
      id: '/workspace/config/compatibility'
      path: '/compatibility'
      fullPath: '/workspace/config/compatibility'
      preLoaderRoute: typeof WorkspaceConfigCompatibilityLayoutRouteImport
      parentRoute: typeof WorkspaceConfigLayoutRoute
    }
    '/workspace/config/client-settings': {
      id: '/workspace/config/client-settings'
      path: '/client-settings'
      fullPath: '/workspace/config/client-settings'
      preLoaderRoute: typeof WorkspaceConfigClientSettingsLayoutRouteImport
      parentRoute: typeof WorkspaceConfigLayoutRoute
    }
    '/workspace/config/caching': {
      id: '/workspace/config/caching'
      path: '/caching'
      fullPath: '/workspace/config/caching'
      preLoaderRoute: typeof WorkspaceConfigCachingLayoutRouteImport
      parentRoute: typeof WorkspaceConfigLayoutRoute
    }
    '/workspace/config/api-keys': {
      id: '/workspace/config/api-keys'
      path: '/api-keys'
      fullPath: '/workspace/config/api-keys'
      preLoaderRoute: typeof WorkspaceConfigApiKeysLayoutRouteImport
      parentRoute: typeof WorkspaceConfigLayoutRoute
    }
    '/workspace/adaptive-routing/settings': {
      id: '/workspace/adaptive-routing/settings'
      path: '/settings'
      fullPath: '/workspace/adaptive-routing/settings'
      preLoaderRoute: typeof WorkspaceAdaptiveRoutingSettingsLayoutRouteImport
      parentRoute: typeof WorkspaceAdaptiveRoutingLayoutRoute
    }
  }
}

interface WorkspaceAdaptiveRoutingLayoutRouteChildren {
  WorkspaceAdaptiveRoutingSettingsLayoutRoute: typeof WorkspaceAdaptiveRoutingSettingsLayoutRoute
}

const WorkspaceAdaptiveRoutingLayoutRouteChildren: WorkspaceAdaptiveRoutingLayoutRouteChildren =
  {
    WorkspaceAdaptiveRoutingSettingsLayoutRoute:
      WorkspaceAdaptiveRoutingSettingsLayoutRoute,
  }

const WorkspaceAdaptiveRoutingLayoutRouteWithChildren =
  WorkspaceAdaptiveRoutingLayoutRoute._addFileChildren(
    WorkspaceAdaptiveRoutingLayoutRouteChildren,
  )

interface WorkspaceConfigLayoutRouteChildren {
  WorkspaceConfigApiKeysLayoutRoute: typeof WorkspaceConfigApiKeysLayoutRoute
  WorkspaceConfigCachingLayoutRoute: typeof WorkspaceConfigCachingLayoutRoute
  WorkspaceConfigClientSettingsLayoutRoute: typeof WorkspaceConfigClientSettingsLayoutRoute
  WorkspaceConfigCompatibilityLayoutRoute: typeof WorkspaceConfigCompatibilityLayoutRoute
  WorkspaceConfigFeatureFlagsLayoutRoute: typeof WorkspaceConfigFeatureFlagsLayoutRoute
  WorkspaceConfigLargePayloadLayoutRoute: typeof WorkspaceConfigLargePayloadLayoutRoute
  WorkspaceConfigLoggingLayoutRoute: typeof WorkspaceConfigLoggingLayoutRoute
  WorkspaceConfigMcpGatewayLayoutRoute: typeof WorkspaceConfigMcpGatewayLayoutRoute
  WorkspaceConfigObservabilityLayoutRoute: typeof WorkspaceConfigObservabilityLayoutRoute
  WorkspaceConfigPerformanceTuningLayoutRoute: typeof WorkspaceConfigPerformanceTuningLayoutRoute
  WorkspaceConfigPricingConfigLayoutRoute: typeof WorkspaceConfigPricingConfigLayoutRoute
  WorkspaceConfigProxyLayoutRoute: typeof WorkspaceConfigProxyLayoutRoute
  WorkspaceConfigSecurityLayoutRoute: typeof WorkspaceConfigSecurityLayoutRoute
}

const WorkspaceConfigLayoutRouteChildren: WorkspaceConfigLayoutRouteChildren = {
  WorkspaceConfigApiKeysLayoutRoute: WorkspaceConfigApiKeysLayoutRoute,
  WorkspaceConfigCachingLayoutRoute: WorkspaceConfigCachingLayoutRoute,
  WorkspaceConfigClientSettingsLayoutRoute:
    WorkspaceConfigClientSettingsLayoutRoute,
  WorkspaceConfigCompatibilityLayoutRoute:
    WorkspaceConfigCompatibilityLayoutRoute,
  WorkspaceConfigFeatureFlagsLayoutRoute:
    WorkspaceConfigFeatureFlagsLayoutRoute,
  WorkspaceConfigLargePayloadLayoutRoute:
    WorkspaceConfigLargePayloadLayoutRoute,
  WorkspaceConfigLoggingLayoutRoute: WorkspaceConfigLoggingLayoutRoute,
  WorkspaceConfigMcpGatewayLayoutRoute: WorkspaceConfigMcpGatewayLayoutRoute,
  WorkspaceConfigObservabilityLayoutRoute:
    WorkspaceConfigObservabilityLayoutRoute,
  WorkspaceConfigPerformanceTuningLayoutRoute:
    WorkspaceConfigPerformanceTuningLayoutRoute,
  WorkspaceConfigPricingConfigLayoutRoute:
    WorkspaceConfigPricingConfigLayoutRoute,
  WorkspaceConfigProxyLayoutRoute: WorkspaceConfigProxyLayoutRoute,
  WorkspaceConfigSecurityLayoutRoute: WorkspaceConfigSecurityLayoutRoute,
}

const WorkspaceConfigLayoutRouteWithChildren =
  WorkspaceConfigLayoutRoute._addFileChildren(
    WorkspaceConfigLayoutRouteChildren,
  )

interface WorkspaceCustomPricingLayoutRouteChildren {
  WorkspaceCustomPricingOverridesLayoutRoute: typeof WorkspaceCustomPricingOverridesLayoutRoute
}

const WorkspaceCustomPricingLayoutRouteChildren: WorkspaceCustomPricingLayoutRouteChildren =
  {
    WorkspaceCustomPricingOverridesLayoutRoute:
      WorkspaceCustomPricingOverridesLayoutRoute,
  }

const WorkspaceCustomPricingLayoutRouteWithChildren =
  WorkspaceCustomPricingLayoutRoute._addFileChildren(
    WorkspaceCustomPricingLayoutRouteChildren,
  )

interface WorkspaceGovernanceLayoutRouteChildren {
  WorkspaceGovernanceAccessProfilesLayoutRoute: typeof WorkspaceGovernanceAccessProfilesLayoutRoute
  WorkspaceGovernanceBusinessUnitsLayoutRoute: typeof WorkspaceGovernanceBusinessUnitsLayoutRoute
  WorkspaceGovernanceCustomersLayoutRoute: typeof WorkspaceGovernanceCustomersLayoutRoute
  WorkspaceGovernanceRbacLayoutRoute: typeof WorkspaceGovernanceRbacLayoutRoute
  WorkspaceGovernanceTeamsLayoutRoute: typeof WorkspaceGovernanceTeamsLayoutRoute
  WorkspaceGovernanceUsersLayoutRoute: typeof WorkspaceGovernanceUsersLayoutRoute
  WorkspaceGovernanceVirtualKeysLayoutRoute: typeof WorkspaceGovernanceVirtualKeysLayoutRoute
}

const WorkspaceGovernanceLayoutRouteChildren: WorkspaceGovernanceLayoutRouteChildren =
  {
    WorkspaceGovernanceAccessProfilesLayoutRoute:
      WorkspaceGovernanceAccessProfilesLayoutRoute,
    WorkspaceGovernanceBusinessUnitsLayoutRoute:
      WorkspaceGovernanceBusinessUnitsLayoutRoute,
    WorkspaceGovernanceCustomersLayoutRoute:
      WorkspaceGovernanceCustomersLayoutRoute,
    WorkspaceGovernanceRbacLayoutRoute: WorkspaceGovernanceRbacLayoutRoute,
    WorkspaceGovernanceTeamsLayoutRoute: WorkspaceGovernanceTeamsLayoutRoute,
    WorkspaceGovernanceUsersLayoutRoute: WorkspaceGovernanceUsersLayoutRoute,
    WorkspaceGovernanceVirtualKeysLayoutRoute:
      WorkspaceGovernanceVirtualKeysLayoutRoute,
  }

const WorkspaceGovernanceLayoutRouteWithChildren =
  WorkspaceGovernanceLayoutRoute._addFileChildren(
    WorkspaceGovernanceLayoutRouteChildren,
  )

interface WorkspaceGuardrailsLayoutRouteChildren {
  WorkspaceGuardrailsConfigurationLayoutRoute: typeof WorkspaceGuardrailsConfigurationLayoutRoute
  WorkspaceGuardrailsProvidersLayoutRoute: typeof WorkspaceGuardrailsProvidersLayoutRoute
}

const WorkspaceGuardrailsLayoutRouteChildren: WorkspaceGuardrailsLayoutRouteChildren =
  {
    WorkspaceGuardrailsConfigurationLayoutRoute:
      WorkspaceGuardrailsConfigurationLayoutRoute,
    WorkspaceGuardrailsProvidersLayoutRoute:
      WorkspaceGuardrailsProvidersLayoutRoute,
  }

const WorkspaceGuardrailsLayoutRouteWithChildren =
  WorkspaceGuardrailsLayoutRoute._addFileChildren(
    WorkspaceGuardrailsLayoutRouteChildren,
  )

interface WorkspaceLogsLayoutRouteChildren {
  WorkspaceLogsConnectorsLayoutRoute: typeof WorkspaceLogsConnectorsLayoutRoute
  WorkspaceLogsMcpLogsLayoutRoute: typeof WorkspaceLogsMcpLogsLayoutRoute
}

const WorkspaceLogsLayoutRouteChildren: WorkspaceLogsLayoutRouteChildren = {
  WorkspaceLogsConnectorsLayoutRoute: WorkspaceLogsConnectorsLayoutRoute,
  WorkspaceLogsMcpLogsLayoutRoute: WorkspaceLogsMcpLogsLayoutRoute,
}

const WorkspaceLogsLayoutRouteWithChildren =
  WorkspaceLogsLayoutRoute._addFileChildren(WorkspaceLogsLayoutRouteChildren)

interface WorkspaceMcpRegistryLayoutRouteChildren {
  WorkspaceMcpRegistryLibraryLayoutRoute: typeof WorkspaceMcpRegistryLibraryLayoutRoute
  WorkspaceMcpRegistryOauthCallbackLayoutRoute: typeof WorkspaceMcpRegistryOauthCallbackLayoutRoute
}

const WorkspaceMcpRegistryLayoutRouteChildren: WorkspaceMcpRegistryLayoutRouteChildren =
  {
    WorkspaceMcpRegistryLibraryLayoutRoute:
      WorkspaceMcpRegistryLibraryLayoutRoute,
    WorkspaceMcpRegistryOauthCallbackLayoutRoute:
      WorkspaceMcpRegistryOauthCallbackLayoutRoute,
  }

const WorkspaceMcpRegistryLayoutRouteWithChildren =
  WorkspaceMcpRegistryLayoutRoute._addFileChildren(
    WorkspaceMcpRegistryLayoutRouteChildren,
  )

interface WorkspaceMcpSessionsLayoutRouteChildren {
  WorkspaceMcpSessionsAuthLayoutRoute: typeof WorkspaceMcpSessionsAuthLayoutRoute
  WorkspaceMcpSessionsAuthFailedLayoutRoute: typeof WorkspaceMcpSessionsAuthFailedLayoutRoute
  WorkspaceMcpSessionsAuthSuccessLayoutRoute: typeof WorkspaceMcpSessionsAuthSuccessLayoutRoute
}

const WorkspaceMcpSessionsLayoutRouteChildren: WorkspaceMcpSessionsLayoutRouteChildren =
  {
    WorkspaceMcpSessionsAuthLayoutRoute: WorkspaceMcpSessionsAuthLayoutRoute,
    WorkspaceMcpSessionsAuthFailedLayoutRoute:
      WorkspaceMcpSessionsAuthFailedLayoutRoute,
    WorkspaceMcpSessionsAuthSuccessLayoutRoute:
      WorkspaceMcpSessionsAuthSuccessLayoutRoute,
  }

const WorkspaceMcpSessionsLayoutRouteWithChildren =
  WorkspaceMcpSessionsLayoutRoute._addFileChildren(
    WorkspaceMcpSessionsLayoutRouteChildren,
  )

interface WorkspacePromptRepoLayoutRouteChildren {
  WorkspacePromptRepoPromptsLayoutRoute: typeof WorkspacePromptRepoPromptsLayoutRoute
}

const WorkspacePromptRepoLayoutRouteChildren: WorkspacePromptRepoLayoutRouteChildren =
  {
    WorkspacePromptRepoPromptsLayoutRoute:
      WorkspacePromptRepoPromptsLayoutRoute,
  }

const WorkspacePromptRepoLayoutRouteWithChildren =
  WorkspacePromptRepoLayoutRoute._addFileChildren(
    WorkspacePromptRepoLayoutRouteChildren,
  )

interface WorkspaceProvidersLayoutRouteChildren {
  WorkspaceProvidersModelLimitsLayoutRoute: typeof WorkspaceProvidersModelLimitsLayoutRoute
  WorkspaceProvidersRoutingRulesLayoutRoute: typeof WorkspaceProvidersRoutingRulesLayoutRoute
}

const WorkspaceProvidersLayoutRouteChildren: WorkspaceProvidersLayoutRouteChildren =
  {
    WorkspaceProvidersModelLimitsLayoutRoute:
      WorkspaceProvidersModelLimitsLayoutRoute,
    WorkspaceProvidersRoutingRulesLayoutRoute:
      WorkspaceProvidersRoutingRulesLayoutRoute,
  }

const WorkspaceProvidersLayoutRouteWithChildren =
  WorkspaceProvidersLayoutRoute._addFileChildren(
    WorkspaceProvidersLayoutRouteChildren,
  )

interface WorkspaceRoutingRulesLayoutRouteChildren {
  WorkspaceRoutingRulesTreeLayoutRoute: typeof WorkspaceRoutingRulesTreeLayoutRoute
}

const WorkspaceRoutingRulesLayoutRouteChildren: WorkspaceRoutingRulesLayoutRouteChildren =
  {
    WorkspaceRoutingRulesTreeLayoutRoute: WorkspaceRoutingRulesTreeLayoutRoute,
  }

const WorkspaceRoutingRulesLayoutRouteWithChildren =
  WorkspaceRoutingRulesLayoutRoute._addFileChildren(
    WorkspaceRoutingRulesLayoutRouteChildren,
  )

interface WorkspaceScimLayoutRouteChildren {
  WorkspaceScimOauthDiscoverCallbackLayoutRoute: typeof WorkspaceScimOauthDiscoverCallbackLayoutRoute
}

const WorkspaceScimLayoutRouteChildren: WorkspaceScimLayoutRouteChildren = {
  WorkspaceScimOauthDiscoverCallbackLayoutRoute:
    WorkspaceScimOauthDiscoverCallbackLayoutRoute,
}

const WorkspaceScimLayoutRouteWithChildren =
  WorkspaceScimLayoutRoute._addFileChildren(WorkspaceScimLayoutRouteChildren)

interface WorkspaceLayoutRouteChildren {
  WorkspaceAdaptiveRoutingLayoutRoute: typeof WorkspaceAdaptiveRoutingLayoutRouteWithChildren
  WorkspaceAlertChannelsLayoutRoute: typeof WorkspaceAlertChannelsLayoutRoute
  WorkspaceAuditLogsLayoutRoute: typeof WorkspaceAuditLogsLayoutRoute
  WorkspaceBrowserAiLayoutRoute: typeof WorkspaceBrowserAiLayoutRoute
  WorkspaceCircuitBreakerLayoutRoute: typeof WorkspaceCircuitBreakerLayoutRoute
  WorkspaceClusterLayoutRoute: typeof WorkspaceClusterLayoutRoute
  WorkspaceComplexityRouterLayoutRoute: typeof WorkspaceComplexityRouterLayoutRoute
  WorkspaceConfigLayoutRoute: typeof WorkspaceConfigLayoutRouteWithChildren
  WorkspaceCustomPricingLayoutRoute: typeof WorkspaceCustomPricingLayoutRouteWithChildren
  WorkspaceDashboardLayoutRoute: typeof WorkspaceDashboardLayoutRoute
  WorkspaceDocsLayoutRoute: typeof WorkspaceDocsLayoutRoute
  WorkspaceGovernanceLayoutRoute: typeof WorkspaceGovernanceLayoutRouteWithChildren
  WorkspaceGuardrailsLayoutRoute: typeof WorkspaceGuardrailsLayoutRouteWithChildren
  WorkspaceLogsLayoutRoute: typeof WorkspaceLogsLayoutRouteWithChildren
  WorkspaceMcpAuthConfigLayoutRoute: typeof WorkspaceMcpAuthConfigLayoutRoute
  WorkspaceMcpGatewayLayoutRoute: typeof WorkspaceMcpGatewayLayoutRoute
  WorkspaceMcpLogsLayoutRoute: typeof WorkspaceMcpLogsLayoutRoute
  WorkspaceMcpRegistryLayoutRoute: typeof WorkspaceMcpRegistryLayoutRouteWithChildren
  WorkspaceMcpSessionsLayoutRoute: typeof WorkspaceMcpSessionsLayoutRouteWithChildren
  WorkspaceMcpSettingsLayoutRoute: typeof WorkspaceMcpSettingsLayoutRoute
  WorkspaceMcpToolGroupsLayoutRoute: typeof WorkspaceMcpToolGroupsLayoutRoute
  WorkspaceModelCatalogLayoutRoute: typeof WorkspaceModelCatalogLayoutRoute
  WorkspaceModelLimitsLayoutRoute: typeof WorkspaceModelLimitsLayoutRoute
  WorkspaceOauthGrantsLayoutRoute: typeof WorkspaceOauthGrantsLayoutRoute
  WorkspaceObservabilityLayoutRoute: typeof WorkspaceObservabilityLayoutRoute
  WorkspacePluginsLayoutRoute: typeof WorkspacePluginsLayoutRoute
  WorkspacePromptRepoLayoutRoute: typeof WorkspacePromptRepoLayoutRouteWithChildren
  WorkspaceProvidersLayoutRoute: typeof WorkspaceProvidersLayoutRouteWithChildren
  WorkspaceRbacLayoutRoute: typeof WorkspaceRbacLayoutRoute
  WorkspaceRoutingRulesLayoutRoute: typeof WorkspaceRoutingRulesLayoutRouteWithChildren
  WorkspaceScimLayoutRoute: typeof WorkspaceScimLayoutRouteWithChildren
  WorkspaceSkillsRepoLayoutRoute: typeof WorkspaceSkillsRepoLayoutRoute
  WorkspaceVirtualKeysLayoutRoute: typeof WorkspaceVirtualKeysLayoutRoute
}

const WorkspaceLayoutRouteChildren: WorkspaceLayoutRouteChildren = {
  WorkspaceAdaptiveRoutingLayoutRoute:
    WorkspaceAdaptiveRoutingLayoutRouteWithChildren,
  WorkspaceAlertChannelsLayoutRoute: WorkspaceAlertChannelsLayoutRoute,
  WorkspaceAuditLogsLayoutRoute: WorkspaceAuditLogsLayoutRoute,
  WorkspaceBrowserAiLayoutRoute: WorkspaceBrowserAiLayoutRoute,
  WorkspaceCircuitBreakerLayoutRoute: WorkspaceCircuitBreakerLayoutRoute,
  WorkspaceClusterLayoutRoute: WorkspaceClusterLayoutRoute,
  WorkspaceComplexityRouterLayoutRoute: WorkspaceComplexityRouterLayoutRoute,
  WorkspaceConfigLayoutRoute: WorkspaceConfigLayoutRouteWithChildren,
  WorkspaceCustomPricingLayoutRoute:
    WorkspaceCustomPricingLayoutRouteWithChildren,
  WorkspaceDashboardLayoutRoute: WorkspaceDashboardLayoutRoute,
  WorkspaceDocsLayoutRoute: WorkspaceDocsLayoutRoute,
  WorkspaceGovernanceLayoutRoute: WorkspaceGovernanceLayoutRouteWithChildren,
  WorkspaceGuardrailsLayoutRoute: WorkspaceGuardrailsLayoutRouteWithChildren,
  WorkspaceLogsLayoutRoute: WorkspaceLogsLayoutRouteWithChildren,
  WorkspaceMcpAuthConfigLayoutRoute: WorkspaceMcpAuthConfigLayoutRoute,
  WorkspaceMcpGatewayLayoutRoute: WorkspaceMcpGatewayLayoutRoute,
  WorkspaceMcpLogsLayoutRoute: WorkspaceMcpLogsLayoutRoute,
  WorkspaceMcpRegistryLayoutRoute: WorkspaceMcpRegistryLayoutRouteWithChildren,
  WorkspaceMcpSessionsLayoutRoute: WorkspaceMcpSessionsLayoutRouteWithChildren,
  WorkspaceMcpSettingsLayoutRoute: WorkspaceMcpSettingsLayoutRoute,
  WorkspaceMcpToolGroupsLayoutRoute: WorkspaceMcpToolGroupsLayoutRoute,
  WorkspaceModelCatalogLayoutRoute: WorkspaceModelCatalogLayoutRoute,
  WorkspaceModelLimitsLayoutRoute: WorkspaceModelLimitsLayoutRoute,
  WorkspaceOauthGrantsLayoutRoute: WorkspaceOauthGrantsLayoutRoute,
  WorkspaceObservabilityLayoutRoute: WorkspaceObservabilityLayoutRoute,
  WorkspacePluginsLayoutRoute: WorkspacePluginsLayoutRoute,
  WorkspacePromptRepoLayoutRoute: WorkspacePromptRepoLayoutRouteWithChildren,
  WorkspaceProvidersLayoutRoute: WorkspaceProvidersLayoutRouteWithChildren,
  WorkspaceRbacLayoutRoute: WorkspaceRbacLayoutRoute,
  WorkspaceRoutingRulesLayoutRoute:
    WorkspaceRoutingRulesLayoutRouteWithChildren,
  WorkspaceScimLayoutRoute: WorkspaceScimLayoutRouteWithChildren,
  WorkspaceSkillsRepoLayoutRoute: WorkspaceSkillsRepoLayoutRoute,
  WorkspaceVirtualKeysLayoutRoute: WorkspaceVirtualKeysLayoutRoute,
}

const WorkspaceLayoutRouteWithChildren = WorkspaceLayoutRoute._addFileChildren(
  WorkspaceLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLayoutRoute: IndexLayoutRoute,
  LoginLayoutRoute: LoginLayoutRoute,
  PprofLayoutRoute: PprofLayoutRoute,
  SignupLayoutRoute: SignupLayoutRoute,
  WorkspaceLayoutRoute: WorkspaceLayoutRouteWithChildren,
  OauthConsentLayoutRoute: OauthConsentLayoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
