{{- if and (eq .Values.storage.mode "postgres") .Values.postgresql.enabled (not .Values.postgresql.external.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "raksha.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "raksha.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "raksha.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
