import { BaseProvider, ConcurrencyAndBufferSize, NetworkConfig } from "@/lib/types/config";
import { ProviderName } from "./logs";

/**
 * Parse a date string in YYYY-MM-DD format with strict validation.
 * Returns null if the string is empty, malformed, or represents an invalid date.
 */
function parseTrialExpiry(dateStr: string | undefined): Date | null {
	if (!dateStr || !dateStr.trim()) return null;

	// Strict format check: YYYY-MM-DD
	const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
	if (!dateRegex.test(dateStr)) return null;

	const [year, month, day] = dateStr.split("-").map(Number);
	const date = new Date(year, month - 1, day);

	// Validate the date components match (catches invalid dates like 2024-02-30)
	if (date.getFullYear() !== year || date.getMonth() !== month - 1 || date.getDate() !== day) {
		return null;
	}

	return date;
}

// Model placeholders based on provider type
export const ModelPlaceholders = {
	default: "e.g. gpt-4, gpt-3.5-turbo. Leave blank for all models.",
	anthropic: "e.g. claude-3-haiku, claude-2.1",
	azure: "e.g. gpt-4, gpt-35-turbo (must match alias keys)",
	bedrock: "e.g. claude-v2, titan-text-express-v1, ai21-j2-mid",
	bedrock_mantle: "e.g. anthropic.claude-opus-4-8, openai.gpt-oss-120b",
	cerebras: "e.g. cerebras-2, cerebras-2-vision",
	cohere: "e.g. command-r, command-r-plus",
	deepseek: "e.g. deepseek-v4-flash, deepseek-v4-pro",
	gemini: "e.g. gemini-1.5-pro, gemini-1.5-flash",
	groq: "e.g. llama3-70b-8192, mixtral-8x7b-32768",
	huggingface: "e.g. sambanova/meta-llama/Llama-3.1-8B-Instruct, nebius/Qwen/Qwen3-Embedding-8B",
	mistral: "e.g. mistral-7b-instruct, mixtral-8x7b",
	openrouter: "e.g. openai/gpt-4, anthropic/claude-3-haiku",
	sgl: "e.g. sgl-2, sgl-vision",
	parasail: "e.g. parasail-2, parasail-vision",
	elevenlabs: "e.g. eleven_multilingual_v2, eleven_turbo_v2",
	perplexity: "e.g. sonar-pro, sonar-deep-research",
	ollama: "e.g. llama3.1, llama2",
	"opencode-go": "e.g. gpt-5.5, claude-sonnet-4-6",
	"opencode-zen": "e.g. gpt-5.5, claude-sonnet-4-6",
	openai: "e.g. gpt-4, gpt-4o, gpt-4o-mini, gpt-3.5-turbo",
	vertex: "e.g. gemini-1.5-pro, text-bison, chat-bison",
	nebius: "e.g. openai/gpt-oss-120b, google/gemma-2-9b-it-fast, Qwen/Qwen2.5-VL-72B-Instruct",
	xai: "e.g. grok-4-0709, grok-3-mini, grok-3, grok-2-vision-1212",
	replicate: "e.g. meta/llama3-1-8b-instruct, black-forest-labs/flux-dev",
	vllm: "e.g. Qwen/Qwen3-0.6B, Qwen/Qwen3-1.5B",
	runway: "e.g. gen4_turbo_image_to_video, gen3a_turbo_image_to_video",
	runware: "e.g. runware:100@1, runware:101@1",
	fireworks: "e.g. accounts/fireworks/models/deepseek-v3p2",
	together: "e.g. model from Together AI",
	siliconflow: "e.g. model from SiliconFlow",
	moonshot: "e.g. model from Moonshot AI",
	minimax: "e.g. model from MiniMax",
	sambanova: "e.g. model from SambaNova",
	deepinfra: "e.g. model from DeepInfra",
	novita: "e.g. model from Novita AI",
	nvidia: "e.g. model from NVIDIA NIM",
	hyperbolic: "e.g. model from Hyperbolic",
	portkey: "e.g. model from Portkey",
	dashscope: "e.g. model from Alibaba DashScope",
	zhipu: "e.g. model from Zhipu AI",
	baichuan: "e.g. model from Baichuan",
	stepfun: "e.g. model from StepFun",
	upstage: "e.g. model from Upstage",
	ai21: "e.g. model from AI21 Labs",
	sakana: "e.g. model from Sakana AI",
	baseten: "e.g. model from Baseten",
	anyscale: "e.g. model from Anyscale",
	lepton: "e.g. model from Lepton AI",
	friendli: "e.g. model from FriendliAI",
	modelscope: "e.g. model from ModelScope",
	hunyuan: "e.g. model from Tencent Hunyuan",
	qianfan: "e.g. model from Baidu Qianfan",
	ark: "e.g. model from Volcengine Ark",
	sarvam: "e.g. model from Sarvam AI",
	krutrim: "e.g. model from Krutrim",
	sensenova: "e.g. model from SenseNova",
	spark: "e.g. model from iFlytek Spark",
	reka: "e.g. model from Reka AI",
	featherless: "e.g. model from Featherless AI",
	scaleway: "e.g. model from Scaleway",
	voyage: "e.g. model from Voyage AI",
	jina: "e.g. model from Jina AI",
	nscale: "e.g. model from Nscale",
	publicai: "e.g. model from PublicAI",
	inferencenet: "e.g. model from Inference.net",
	kluster: "e.g. model from Kluster AI",
	lingyiwanwu: "e.g. model from Lingyi Wanwu",
	inceptionlabs: "e.g. model from Inception Labs",
	arcee: "e.g. model from Arcee AI",
	nousresearch: "e.g. model from Nous Research",
	morphllm: "e.g. model from MorphLLM",
	nlpcloud: "e.g. model from NLP Cloud",
	monsterapi: "e.g. model from MonsterAPI",
	aionlabs: "e.g. model from AionLabs",
	totalgpt: "e.g. model from TotalGPT",
	mancer: "e.g. model from Mancer",
	dit: "e.g. model from Dit.ai",
	opper: "e.g. model from Opper",
	relace: "e.g. model from Relace",
	openadapter: "e.g. model from OpenAdapter",
	nanogpt: "e.g. model from Nano-GPT",
	nararouter: "e.g. model from NaraRouter",
	navy: "e.g. model from Navy AI",
	freemodel: "e.g. model from FreeModel",
	freeai: "e.g. model from Free.ai",
	freeinference: "e.g. model from FreeInference",
	fenay: "e.g. model from Fenay AI",
	empower: "e.g. model from Empower AI",
	fastinfra: "e.g. model from FastInfra",
	wafer: "e.g. model from Wafer",
	gmiserving: "e.g. model from GMI Serving",
	cerebrium: "e.g. model from Cerebrium",
	dashscopecn: "e.g. model from DashScope China",
};

export const isKeyRequiredByProvider: Record<ProviderName, boolean> = {
	anthropic: true,
	azure: true,
	bedrock: true,
	bedrock_mantle: true,
	cerebras: true,
	cohere: true,
	deepseek: true,
	gemini: true,
	groq: true,
	huggingface: true,
	mistral: true,
	openrouter: true,
	sgl: false,
	parasail: true,
	elevenlabs: true,
	ollama: false,
	"opencode-go": true,
	"opencode-zen": true,
	openai: true,
	vertex: true,
	perplexity: true,
	nebius: true,
	xai: true,
	replicate: true,
	runway: true,
	runware: true,
	vllm: false,
	fireworks: true,
	together: true,
	siliconflow: true,
	moonshot: true,
	minimax: true,
	sambanova: true,
	deepinfra: true,
	novita: true,
	nvidia: true,
	hyperbolic: true,
	portkey: true,
	dashscope: true,
	zhipu: true,
	baichuan: true,
	stepfun: true,
	upstage: true,
	ai21: true,
	sakana: true,
	baseten: true,
	anyscale: true,
	lepton: true,
	friendli: true,
	modelscope: true,
	hunyuan: true,
	qianfan: true,
	ark: true,
	sarvam: true,
	krutrim: true,
	sensenova: true,
	spark: true,
	reka: true,
	featherless: true,
	scaleway: true,
	voyage: true,
	jina: true,
	nscale: true,
	publicai: true,
	inferencenet: true,
	kluster: true,
	lingyiwanwu: true,
	inceptionlabs: true,
	arcee: true,
	nousresearch: true,
	morphllm: true,
	nlpcloud: true,
	monsterapi: true,
	aionlabs: true,
	totalgpt: true,
	mancer: true,
	dit: true,
	opper: true,
	relace: true,
	openadapter: true,
	nanogpt: true,
	nararouter: true,
	navy: true,
	freemodel: true,
	freeai: true,
	freeinference: true,
	fenay: true,
	empower: true,
	fastinfra: true,
	wafer: true,
	gmiserving: true,
	cerebrium: true,
	dashscopecn: true,
};

export const DefaultNetworkConfig = {
	base_url: "",
	default_request_timeout_in_seconds: 300,
	max_retries: 0,
	retry_backoff_initial: 1000,
	retry_backoff_max: 10000,
	insecure_skip_verify: false,
	ca_cert_pem: { value: "", ref: "" },
	stream_idle_timeout_in_seconds: 120,
	max_conns_per_host: 5000,
	enforce_http2: false,
	allow_private_network: false,
} satisfies NetworkConfig;

export const DefaultPerformanceConfig = {
	concurrency: 1000,
	buffer_size: 5000,
} satisfies ConcurrencyAndBufferSize;

export const MCP_STATUS_COLORS: Record<string, string> = {
	connected: "bg-green-100 text-green-800",
	error: "bg-red-100 text-red-800",
	disconnected: "bg-gray-100 text-gray-800",
	pending_tools: "bg-yellow-100 text-yellow-800",
	disabled: "bg-orange-100 text-orange-800",
};

// Mapping of what IS supported by each base provider
export const PROVIDER_SUPPORTED_REQUESTS: Record<BaseProvider, string[]> = {
	openai: [
		"list_models",
		"text_completion",
		"text_completion_stream",
		"chat_completion",
		"chat_completion_stream",
		"responses",
		"responses_stream",
		"responses_retrieve",
		"responses_delete",
		"responses_cancel",
		"responses_input_items",
		"embedding",
		"speech",
		"speech_stream",
		"transcription",
		"transcription_stream",
		"image_generation",
		"image_generation_stream",
		"image_edit",
		"image_edit_stream",
		"image_variation",
		"count_tokens",
		"video_generation",
		"video_retrieve",
		"video_download",
		"video_delete",
		"video_list",
		"video_remix",
	],
	anthropic: ["list_models", "chat_completion", "chat_completion_stream", "responses", "responses_stream", "count_tokens"],
	gemini: [
		"list_models",
		"chat_completion",
		"chat_completion_stream",
		"responses",
		"responses_stream",
		"embedding",
		"transcription",
		"transcription_stream",
		"speech",
		"speech_stream",
		"image_generation",
		"image_edit",
		"count_tokens",
		"video_generation",
		"video_retrieve",
		"video_download",
		"video_delete",
		"video_list",
		"video_remix",
	],
	cohere: ["list_models", "chat_completion", "chat_completion_stream", "responses", "responses_stream", "embedding", "count_tokens"],
	bedrock: [
		"list_models",
		"text_completion",
		"chat_completion",
		"chat_completion_stream",
		"responses",
		"responses_stream",
		"embedding",
		"image_generation",
		"image_edit",
		"image_variation",
	],
	replicate: [
		"list_models",
		"text_completion",
		"chat_completion",
		"chat_completion_stream",
		"responses",
		"responses_stream",
		"image_generation",
		"image_generation_stream",
		"image_edit",
		"image_edit_stream",
		"video_generation",
		"video_retrieve",
		"video_download",
		"video_delete",
		"video_list",
		"video_remix",
	],
	fireworks: [
		"list_models",
		"text_completion",
		"text_completion_stream",
		"chat_completion",
		"chat_completion_stream",
		"responses",
		"responses_stream",
		"embedding",
	],
};

export const IS_ENTERPRISE = process.env.UNIFAI_IS_ENTERPRISE === "true";
export const TRIAL_EXPIRY = parseTrialExpiry(process.env.UNIFAI_ENTERPRISE_TRIAL_EXPIRY);

/** Dashboard branding — override via UNIFAI_COMPANY_NAME / UNIFAI_COMPANY_LOGO in .env. */
export const COMPANY_NAME = (process.env.UNIFAI_COMPANY_NAME || "YesPanchi Group of Companies").trim() || "YesPanchi Group of Companies";
/** Official YesPanchi mark (public/yes-panchi-logo.png). GIF source also at /yes-panchi-logo.gif. */
export const COMPANY_LOGO = (process.env.UNIFAI_COMPANY_LOGO || "/yes-panchi-logo.png").trim() || "/yes-panchi-logo.png";
export const COMPANY_SHORT_NAME = COMPANY_NAME.split(/\s+/)[0] || "YesPanchi";