apiVersion: v2
name: raksha
description: A Helm chart for deploying Raksha - AI Gateway with unified interface for multiple providers
type: application
version: 2.1.25
appVersion: "1.5.12"
keywords:
  - ai
  - gateway
  - llm
  - openai
  - anthropic
home: https://www.getmaxim.ai/raksha
sources:
  - https://github.com/raksha/raksha
maintainers:
  - name: Raksha Team
    email: support@getraksha.ai
icon: https://www.getraksha.ai/favicon.png
