package handlers

import (
	"archive/zip"
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/valyala/fasthttp"
)

const guardConfigFileName = "raksha_guard_config.json"

type buildAsset struct {
	name string
	path string
}

// guardBuildMu serializes "Build now" so two admins cannot write the same release ZIP at once.
var guardBuildMu sync.Mutex

// freshGuardConfig re-derives the server-specific Guard config fields from the running
// server's environment (the same .env values sync_config_from_env.py uses), keeping any
// other fields from the shipped config.
func freshGuardConfig() ([]byte, error) {
	cfg := map[string]any{}
	if p, ok := findFirstExisting(browserAISetupCandidates()[guardConfigFileName]); ok {
		if data, err := os.ReadFile(p); err == nil {
			_ = json.Unmarshal([]byte(strings.TrimPrefix(string(data), "\ufeff")), &cfg)
		}
	}
	if domain := strings.TrimRight(strings.TrimSpace(os.Getenv("SERVER_DOMAIN")), "/"); domain != "" {
		cfg["backend_url"] = domain
		cfg["pac_url"] = domain + "/api/browser-ai/pac"
	} else if v, _ := cfg["backend_url"].(string); v == "" {
		return nil, errors.New("SERVER_DOMAIN is not set in .env")
	}
	if v := strings.TrimSpace(os.Getenv("RAKSHA_PROXY_ADDR")); v != "" {
		cfg["proxy_addr"] = v
	}
	if v := strings.TrimSpace(os.Getenv("PAC_HTTP_PORT")); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			cfg["pac_http_port"] = n
		} else {
			cfg["pac_http_port"] = v
		}
	}
	if secret := configuredGuardSecret(); secret != "" {
		cfg["guard_secret"] = secret
	} else if guardSecretRequired() {
		return nil, errors.New("RAKSHA_GUARD_SECRET is not set in .env — refusing to build a package without the Guard secret")
	}
	cfg["_comment"] = "Generated by the Raksha server (Browser AI → Setup → Build now) from .env"
	out, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(out, '\n'), nil
}

// writeReleaseFileAtomic replaces path via a temp file in the same directory, so a download of the
// previous package never sees a half-written file.
func writeReleaseFileAtomic(path string, write func(io.Writer) error) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".*.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	bw := bufio.NewWriterSize(tmp, 1<<20)
	werr := write(bw)
	if werr == nil {
		werr = bw.Flush()
	}
	if cerr := tmp.Close(); werr == nil {
		werr = cerr
	}
	if werr == nil {
		_ = os.Chmod(tmpName, 0o644)
		werr = os.Rename(tmpName, path)
	}
	if werr != nil {
		_ = os.Remove(tmpName)
	}
	return werr
}

// buildWindowsPackage writes release/Raksha_Guard_Windows.zip from the shipped Setup/portable
// EXEs plus a fresh config and the current helper files. Setup.exe installs a
// raksha_guard_config.json found next to it in place of the one it was compiled with.
func buildWindowsPackage(config []byte) (string, error) {
	setupPath, setupOK := findFirstExisting(browserAISetupCandidates()["Raksha_Guard_Setup.exe"])
	exePath, exeOK := findFirstExisting(browserAISetupCandidates()["Raksha_Guard.exe"])
	if !setupOK && !exeOK {
		return "", errors.New("no Windows Guard EXE on server — upload Raksha_Guard_Setup.exe / Raksha_Guard.exe to apps/browser-guard/release/ (tools/upload_guard_release.ps1 or the 1Panel file manager)")
	}
	releaseDir := filepath.Dir(setupPath)
	if !setupOK {
		releaseDir = filepath.Dir(exePath)
	}
	var assets []buildAsset
	if setupOK {
		assets = append(assets, buildAsset{name: "Raksha_Guard_Setup.exe", path: setupPath})
	}
	if exeOK {
		assets = append(assets, buildAsset{name: "Raksha_Guard.exe", path: exePath})
	}
	for _, name := range []string{"INSTALL_WINDOWS.txt", "VERSION.txt", "Update_Raksha_Guard.ps1", "Uninstall_Raksha_Guard.bat"} {
		if p, ok := findFirstExisting(browserAISetupCandidates()[name]); ok {
			assets = append(assets, buildAsset{name: name, path: p})
		}
	}
	out := filepath.Join(releaseDir, "Raksha_Guard_Windows.zip")
	err := writeReleaseFileAtomic(out, func(w io.Writer) error {
		zw := zip.NewWriter(w)
		for _, a := range assets {
			method := zip.Deflate
			if strings.HasSuffix(strings.ToLower(a.name), ".exe") {
				method = zip.Store
			}
			entry, err := zw.CreateHeader(&zip.FileHeader{Name: a.name, Method: method, Modified: time.Now()})
			if err != nil {
				return err
			}
			f, err := os.Open(a.path)
			if err != nil {
				return err
			}
			_, err = io.Copy(entry, f)
			f.Close()
			if err != nil {
				return err
			}
		}
		entry, err := zw.CreateHeader(&zip.FileHeader{Name: guardConfigFileName, Method: zip.Deflate, Modified: time.Now()})
		if err != nil {
			return err
		}
		if _, err := entry.Write(config); err != nil {
			return err
		}
		return zw.Close()
	})
	if err != nil {
		return "", err
	}
	_ = writeReleaseFileAtomic(filepath.Join(releaseDir, guardConfigFileName), func(w io.Writer) error {
		_, err := w.Write(config)
		return err
	})
	return out, nil
}

// buildMacPackage rewrites release/Raksha_Guard_macOS.zip with a fresh config and the current
// helper scripts. The .app itself is reused: it can only be compiled on a Mac.
func buildMacPackage(config []byte) (string, error) {
	macZipPath, ok := findFirstExisting(browserAISetupCandidates()["Raksha_Guard_macOS.zip"])
	if !ok {
		return "", errors.New("no macOS Guard package on server — upload Raksha_Guard_macOS.zip to apps/browser-guard/release/ (tools/upload_guard_release.ps1 or the 1Panel file manager)")
	}
	if err := writeReleaseFileAtomic(macZipPath, func(w io.Writer) error {
		return writeMacZipWithHelpers(w, macZipPath, config)
	}); err != nil {
		return "", err
	}
	return macZipPath, nil
}

// buildAndServeSetupPackage handles "Build now": refresh the package on the server, publish
// the latest Guard code bundle, save the ZIP as the new release, and stream it back.
func (h *BrowserAIHandler) buildAndServeSetupPackage(ctx *fasthttp.RequestCtx, platform string) {
	if !h.requireGuardAdmin(ctx, "Admin role required to build Guard packages") {
		return
	}
	isMac := platform == "mac" || platform == "macos" || platform == "darwin"
	if !isMac && platform != "windows" && platform != "win" {
		SendError(ctx, fasthttp.StatusBadRequest, "platform must be windows or mac for Build now")
		return
	}
	guardBuildMu.Lock()
	defer guardBuildMu.Unlock()
	started := time.Now()

	config, err := freshGuardConfig()
	if err != nil {
		SendError(ctx, fasthttp.StatusBadRequest, "Build failed: "+err.Error())
		return
	}
	var (
		zipPath, fileName, version string
	)
	if isMac {
		zipPath, err = buildMacPackage(config)
		fileName, version = "Raksha_Guard_macOS.zip", readGuardMacReleaseVersion()
	} else {
		zipPath, err = buildWindowsPackage(config)
		fileName, version = "Raksha_Guard_Windows.zip", readGuardReleaseVersion()
	}
	bundle, bundleMsg := publishProxyBundleSummary()
	resp := map[string]any{
		"mode":          "build-now",
		"version":       readGuardReleaseVersion(),
		"mac_version":   readGuardMacReleaseVersion(),
		"windows_ready": !isMac && err == nil,
		"macos_ready":   isMac && err == nil,
		"proxy_bundle":  bundle,
	}
	if err != nil {
		resp["message"] = fmt.Sprintf("Build now (%s) failed: %v", platform, err)
		h.recordRebuild(ctx, started, "failed", resp, "")
		SendError(ctx, fasthttp.StatusInternalServerError, resp["message"].(string))
		return
	}
	resp["message"] = fmt.Sprintf("Build now (%s): %s rebuilt with the current server config. %s", platform, fileName, bundleMsg)
	status := "success"
	if _, failed := bundle["error"]; failed {
		status = "failed"
	}
	h.recordRebuild(ctx, started, status, resp, "")

	f, err := os.Open(zipPath)
	if err != nil {
		SendError(ctx, fasthttp.StatusInternalServerError, "Build finished but the package could not be read: "+err.Error())
		return
	}
	ctx.SetStatusCode(fasthttp.StatusOK)
	ctx.SetContentType("application/zip")
	ctx.Response.Header.Set("Content-Disposition", `attachment; filename="`+fileName+`"`)
	if version != "" {
		setGuardVersionHeaders(ctx, version)
	}
	ctx.SetBodyStreamWriter(func(w *bufio.Writer) {
		defer f.Close()
		_, _ = io.Copy(w, f)
		_ = w.Flush()
	})
}
